Content/Blueprints/DataTables/DunShop/ShopItemDataTable.uasset, Content/Blueprints/Widgets/DunShop/WBP_DunItemWidget.uasset, Content/Blueprints/Widgets/DunShop/WBP_DunShopWidget.uasset, Source/RogShop/Widget/DunShop/DunItemWidget.cpp, Source/RogShop/Widget/DunShop/DunItemWidget.h, Source/RogShop/Widget/DunShop/DunShopWidget.cpp, Source/RogShop/Widget/DunShop/DunShopWidget.h, Source/RogShop/Widget/DunShop/ShopItemStruct.cpp, Source/RogShop/Widget/DunShop/ShopItemStruct.h
- #3
- 일반 (Common, 60프로), 고급 (Rare, 25프로), 희귀 (Epic, 10프로), 전설 (Legendary, 5프로) 확률로 상점에 아이템 출현되도록 구현
- 현재는 데이터 테이블에 Sword랑 Potion 아이템만 각 등급별로 존재, 추후 내용 추가 필요
- 아이템 이름, 사진, 설명, 가격, 보유 골드 및 나가기 버튼이 상점 UI에 반영된 상태
- 사진은 언리얼에 기본적으로 있는 임시 사진을 데이터 테이블에 넣어둔 상태
=> [Update] 아이템 데이터 테이블을 이용하여 등급에 따른 확률 적용을 통한 랜덤 상점 아이템 생성 로직 구현

Content/Assets/Animations/PlayerCharacter/OneHand_Sword_Idle.uasset, Content/Assets/Animations/PlayerCharacter/OneHand_Sword_strafe_run_F.uasset, Content/Blueprints/AnimInstance/ABP_DunPlayerAnim.uasset, Content/Blueprints/AnimInstance/ABP_SwordDunPlayerAnim.uasset, Content/Blueprints/AnimInstance/ALI_LinkedLayer.uasset, Content/Blueprints/Characters/BP_DunPlayerCharacter.uasset
추후에 무기별 애니메이션을 위해 AnimLayerInterface로 기존 애니메이션 로직 수정
Idle 및 Walk에 대해 사용.
링크된 레이어가 없을 경우 기존의 기본 애니메이션이 재생되도록 구현
링크할 레이어의 예시로, 검을 착용하고 있는 애니메이션이나 창을 들고 있는 애니메이션이 있을 수 있다.
=> [Fix] 애니메이션을 AnimLayerInterface을 사용하도록 구현

Content/Blueprints/DataTables/DunShop/ShopItemDataTable.uasset, Content/Blueprints/GameInstance/BP_RSGameInstance.uasset, Source/RogShop/GameInstance/RSGameInstance.cpp, Source/RogShop/GameInstance/RSGameInstance.h, Source/RogShop/RogShop.Build.cs, Source/RogShop/Widget/DunShop/DunItemWidget.cpp, Source/RogShop/Widget/DunShop/DunItemWidget.h, Source/RogShop/Widget/DunShop/DunShopWidget.cpp, Source/RogShop/Widget/DunShop/DunShopWidget.h, Source/RogShop/Widget/DunShop/ShopItemStruct.h
- #3 
1. ShopItemStruct 구조체 기본값 추가
2. 물약 구매시 현재 HP 증가 로직 추가, 캐릭터에서 HP를 Set 해주는 함수 또는 변수 public화 필요
3. 아이템 생성시 중복 생성 X 및 이미 구매한 아이템도 생성 안 되도록 구현
- 처음엔 구매한 아이템이 없으므로 최소 1, 최대 5개의 아이템 생성. 구매 이후부턴 최소 0 (이미 구매한 아이템이 상점에 5번 뜬 경우), 최대 5개의 아이템 생성
4. 구매했던 아이템 데이터 저장을 위한 GameInstance 생성, 공용으로 GameInstance 사용 필요시 해당 파일 사용해야할 수 있음
- 현재 프로젝트 세팅에 넣어두지는 않은 상태
=> [Update] 아이템 적용 로직 일부 추가 및 물품 중복 생성 방지 로직 구현

Content/Blueprints/Actor/Dungeon/BP_SwordWeapon.uasset, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp
무기 슬롯이라는 개념으로, 플레이어 캐릭터가 무기로 2개 가지고있을 수 있도록 구현한다.
1번 무기를 들고 있을 경우 2번 슬롯을 선택했을 때 2번 슬롯의 무기로 전환되도록 구현
무기가 하나도 없을 때 무기를 획득하면 1번 슬롯부터 무기가 추가된다.
이때, 무기를 바로 들고있지 않는다.
1번 무기를 들고 있을 때 해당 무기를 버린다면, 맨손이 된다.
=> [Update] 플레이어 캐릭터에 무기 슬롯 구현 및 무기 전환 로직 구현

Content/Assets/StylizedKnightsWeapons/Meshes/SKM_KnightBattleaxe.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SKM_KnightGreatsword.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SKM_KnightHammer.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SKM_KnightHatchet.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SKM_KnightMace.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SK_KnightBattleaxe.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SK_KnightGreatsword.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SK_KnightHammer.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SK_KnightHatchet.uasset, Content/Assets/StylizedKnightsWeapons/Meshes/SK_KnightMace.uasset, Content/Assets/StylizedKnightsWeapons/Textures/Battleaxe/M_KnightBattleaxe_Steel.uasset, Content/Assets/StylizedKnightsWeapons/Textures/Greatsword/M_KnightGreatsword_Steel.uasset, Content/Assets/StylizedKnightsWeapons/Textures/Hammer/M_KnightHammer_Steel.uasset, Content/Assets/StylizedKnightsWeapons/Textures/Hammer/M_KnightHammer_Steel_Damaged.uasset, Content/Assets/StylizedKnightsWeapons/Textures/Hatchet/M_KnightHatchet_Steel.uasset, Content/Assets/StylizedKnightsWeapons/Textures/Mace/M_KnighMace_Steel.uasset, Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon1.uasset, Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon2.uasset, Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon3.uasset, Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon4.uasset, Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon5.uasset, Content/Blueprints/Actor/Dungeon/BP_SwordWeapon.uasset
승길님의 요청으로 프로토타입의 무기 액터를 추가
BaseWeapon을 상속받는 블루프린트로 스켈레탈 메시에 무기 메시를 적용했다.
애니메이션과 관련된 애셋은 적용되지 않은 상태.
현재 무기 메시가 스태틱 메시로만 존재하여 스켈레탈 메시를 추가했다.
=> [Update] 프로토타입 무기 액터 추가

Source/RogShop/Character/RSDunPlayerCharacter.cpp
`InteractTrace` 함수 실행시 기존에는 가장 마지막에 찾던 액터가 저장되고 값이 변경되지 않는다는 문제가 있었다.
액터를 찾지 못했을 때 찾은 액터를 저장하던 `InteractActor` 의 값을 nullptr로 변경하도록 수정했다.
=> [BugFix] InteractTrace의 찾은 액터를 계속 저장하고 있던 오류 수정

Content/Blueprints/Navigate/PatrolPoint.uasset
충돌해결중에 채널이 변경되어 해당 클래스에서 오버랩이 필요해서 수정되었음
=> [Fix] PatrolPoint 가 올바른 채널에서 오버랩 되도록 수정

Content/Blueprints/AL_Blueprints.uasset, Content/Datas/AL_Datas.uasset
primary asset label 을 사용하여 데이터 테이블이 패키징에 포함될 수 있도록 설정
데이터 테이블과 함께 기존 Blueprints에 있는 블루프린트 클래스들도 패키징에 포함되도록 설정해주었다.
=> [Fix] 데이터테이블이 패키징에 추가되지 않는 문제 해결

Content/Blueprints/Characters/BP_DunPlayerCharacter.uasset, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h
던전 플레이어 캐릭터에 UAIPerceptionStimuliSourceComponent 컴포넌트 추가
bAutoRegister의 값을 true로 설정하여 해당 액터가 생성 및 스폰 됐을 때 감지 시스템에 자동으로 등록 되도록 설정
RegisterForSense으로 시야 감각을 자극원으로 설정
에디터에는 해당 자극원이 추가됐다고 표기되는 변경사항이 없다.
런타임 중에 반영되기 때문으로 보인다.
=> [Update] 던전 플레이어 캐릭터에 AI퍼셉션 자극 소스 추가

Source/RogShop/Character/RSDunBaseCharacter.cpp, Source/RogShop/Character/RSDunBaseCharacter.h, Source/RogShop/Character/RSDunMonsterCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.cpp
스탯 관련한 함수 추가
- float GetMaxHP() const;
- void IncreaseMaxHP(float Amount);
- void DecreaseMaxHP(float Amount);
- float GetHP() const;
- void IncreaseHP(float Amount);
- void DecreaseHP(float Amount);
기존의 체력과 이동속도는 private로 변경
접근제어 지정자를 변경함에 따라 기존 로직에서 변수를 사용한 경우 코드 수정
ARSDunPlayerCharacter의 TakeDamage
ARSDunMonsterCharacter의 TakeDamage
죽었는지 상태를 나타내는 변수 bIsDead 추가
해당 변수와 관련된 함수 추가
- bool GetIsDead();
- virtual void OnDeath();
- 해당 함수는 체력이 0이되면 호출하도록한다.
ARSDunMonsterCharacter에서 OnDeath를 overrdie하도록 해야한다.
=> [Update] 던전 캐릭터의 체력 관련 함수 구현 및 bIsDead 변수 추가

Source/RogShop/Actor/NPC/RSDunShopNpcActor.cpp, Source/RogShop/CheatManager/RSCheatManager.cpp, Source/RogShop/Widget/DunShop/DunItemWidget.cpp, Source/RogShop/Widget/DunShop/DunShopWidget.cpp
- #3 
- 유물 적용 관련 로직은 유물 데이터를 어떻게 보유하고 있을지 결정된 후에 구현 예정
=> [Update] 플레이어 체력 즉시 회복 아이템 구매시 내용 적용되도록 로직 추가 및 불필요한 로그 출력 제거

Source/RogShop/Character/RSDunPlayerCharacter.cpp
#91 
플레이어 캐릭터가 사망한 경우 UAIPerceptionStimuliSourceComponent에 등록된 자극 센서를 모두 제거하도록 로직 추가
하지만, 현재 타겟을 발견한 경우 타겟을 제거하는 로직이 없기 때문에 플레이어를 항상 쫓아간다.
즉, 플레이어 캐릭터가 사망해도 계속 추적한다.
=> [Update] 플레이어 캐릭터가 사망시 등록 했던 자극 센서 제거

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/Character/RSDunBaseCharacter.cpp, Source/RogShop/Character/RSDunBaseCharacter.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h
https://github.com/NbcampUnreal/2nd-Team1-Final-Project/issues/95
플레이어 캐릭터 스탯 개념 구현
- 체력
- 이동속도
- 공격속도
- 캐릭터 공격력, 무기 공격력
- 무기 공격력의 경우 무기가 가집니다.
체력, 공격속도, 공격력은 Increase, Decrease함수로 값을 변경하도록 했습니다.  
체력 및 공격 속도의 경우 값의 범위를 지정해주었습니다.
공격 속도는 공격 애니메이션 재생시 사용합니다.
기존에 공격 애니메이션을 재생시키던 로직에 적용했습니다.
이동 속도의 값 변경시 바로 캐릭터의 이동속도를 변경시키도록 함수를 구현했습니다.
=> [Update] 플레이어 캐릭터에 스탯 구현

Source/RogShop/Actor/MapGenerator/MapGenerator.cpp, Source/RogShop/Actor/MapGenerator/MapGenerator.h
기존 맵 생성방식에서 생성 위치에 따라서 타일의 모양이 바뀔수 있도록 변경(ㅣ,ㅜ,ㄴ,+,막다른길 타일) 및 보스룸까지는 길이 이어질수 있도록 추가로 생성되는 길에서는 50%확률로 막다른길이 나타날수 있도록 변경
=> [Update] 맵 생성 로직 변경 및 업데이트

Content/Blueprints/Actor/BP_InteractableLevelTravel.uasset, Source/RogShop/Actor/RSInteractableLevelTravel.cpp, Source/RogShop/Actor/RSInteractableLevelTravel.h
상호작용을 통해 레벨을 이동하는 액터 추가
소프트 레퍼런스로 저장하면 로직이 좀 더 복잡하고, 레벨의 수가 많지 않기 때문에 메모리에 항상 로드되어있어도 문제가 되지 않을 것 으로 판단된다.
간단한 로직으로 레벨의 이동을 빠르게 구현하기 위해서 레벨을 하드 레퍼런스로 저장합니다.
나중에 필요한 경우 소프트 레퍼런스로 전환하고자 합니다.
하드 레퍼런스를 사용했을 때 참조된 레벨에서 참조중인 액터가 있는 레벨로 이동할 때 에러가 나면서 프로그램이 터지는 문제가 있었습니다.
메모리 문제인 것 같기 때문에 TWeakObjectPtr을 사용했고, 문제는 해결했습니다.
나중에 레벨 이동 전에 세이브하는 기능이 필요합니다.
=> [Add] 레벨 이동을 위한 액터 구현

Content/Blueprints/GameMode/BP_BaseAreaGameMode.uasset, Content/Maps/BaseAreaMap.umap, Source/RogShop/Actor/RSInteractableLevelTravel.cpp, Source/RogShop/Actor/RSInteractableLevelTravel.h, Source/RogShop/GameModeBase/RSBaseAreaGameModeBase.cpp, Source/RogShop/GameModeBase/RSBaseAreaGameModeBase.h
거점 레벨 추가
- BaseAreaMap
거점 레벨을 위한 게임모드 추가
- RSBaseAreaGameModeBase
- BP_RSBaseAreaGameMode
기존 레벨 이동 액터에서 레벨을 TWeakObjectPtr을 사용했는데, 참조가 사라지는 문제가 있어서 TSoftObjectPtr을 사용했습니다.
이에 따라 레벨을 이동하기 위해 참조된 애셋의 이름을 가져오는 로직을 수정하였습니다.
=> [Update] 거점 레벨 추가 및 게임모드 추가와 기존 레벨 이동 액터 버그 수정

Content/Assets/StylizedCreaturesBundle/AnimMontage/AM_Boar_Attack1.uasset, Content/Assets/StylizedCreaturesBundle/AnimMontage/AM_Boar_Death.uasset, Content/Assets/UndeadPack/SkeletonEnemy/AnimMontage/AM_Skeleton_Attack_1.uasset, Content/Assets/UndeadPack/SkeletonEnemy/AnimMontage/AM_Skeleton_Death.uasset, Content/Blueprints/AnimInstance/ABP_RSDunBoarAnim.uasset, Content/Blueprints/AnimInstance/ABP_RSDunSkeletonAnim.uasset, Content/Blueprints/Characters/BP_RSDunBoarCharacter.uasset, Content/Blueprints/Characters/BP_RSDunSkeletonCharacter.uasset, Source/RogShop/Character/Monster/RSDunBoarCharacter.cpp, Source/RogShop/Character/Monster/RSDunBoarCharacter.h, Source/RogShop/Character/Monster/RSDunSkeletonCharacter.cpp, Source/RogShop/Character/Monster/RSDunSkeletonCharacter.h, Source/RogShop/CheatManager/RSCheatManager.cpp
- #108 
공격, 죽음 애님 몽타주 연결 및 함수 구현
달리기는 각 몬스터의 애님 인스턴스를 상속받는 애니메이션 블루프린트의 애님 그래프에서 StateMachine을 활용해 구현
숲 일반 몬스터 - 멧돼지(boar)
광산 일반 몬스터 - 스켈레톤(skeleton)
위 두 몬스터의 캐릭터 블루프린트와 애니메이션 블루프린트를 생성했습니다.
애니메이션 블루프린트는 RSDunMonsterAnimInstance.cpp를 기반으로 각 몬스터들마다 고유의 애님 BP를 갖도록 하였습니다.
ㄴ 왜냐하면 타겟 스켈레톤이 달라서 그렇게 했습니다.
치트매니저로 애니메이션이 잘 나오는 지 테스트까지 완료했습니다.
=> [Add] Boar와 Skeleton 몬스터 캐릭터 블루프린트와 애니메이션 블루프린트 생성

Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_Attack1.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_Death.uasset, Content/Blueprints/AnimInstance/ABP_RSDunBossFlowerAnim.uasset, Content/Blueprints/Characters/BP_RSDunBossFlowerCharacter.uasset, Content/Blueprints/Characters/BP_RSDunBossWormCharacter.uasset, Source/RogShop/Character/Monster/RSDunBossFlowerCharacter.cpp, Source/RogShop/Character/Monster/RSDunBossFlowerCharacter.h, Source/RogShop/Character/Monster/RSDunBossWormCharacter.cpp, Source/RogShop/Character/Monster/RSDunBossWormCharacter.h, Source/RogShop/CheatManager/RSCheatManager.cpp
- #108 
- 공격, 죽음은 애님 몽타주 연결 및 함수 구현
- Idle 상태는 각 몬스터의 애님 인스턴스를 상속 받는 애니메이션 블루프린트의 애님 그래프에서 StateMachine을 활용해 구현
- 사막 보스는 수,목요일 저녁까지 알집 파일로 올려주신다고 확인 받음.
- 그래서 숲 보스인 거대 꽃만 일단 구현함.
=> [Feature] 던전(숲) 보스 몬스터 1마리의 공격, 죽음 애니메이션 구현

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.h
EWeaponSlot을 0-based에서 1-based로 변경하며, 변경된 값에 따라 로직을 수정했습니다.
Enum class의 0번 값은 NONE으로 사용하기로 정했기 때문에 해당 값들을 변경해주었습니다.
다음과 같은 상황에서의 버그를 수정해주었습니다.
- 무기 슬롯은 가득 찼고, 착용 중인 무기가 없을 때 추가적으로 무기를 획득하는 경우
- 장착하려는 슬롯에 무기가 없는 경우
- 장착하려는 슬롯이 이미 장착 중인 경우
위의 버그는 조건식을 사용하여 해결했습니다.
=> [Bugfix] 무기 슬롯 시스템에 있던 버그 수정

Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h
#93 
기존 플레이어 캐릭터는 라인 트레이스를 사용하여 충돌된 액터를 찾는데, 다른 액터의 충돌체 크기가 너무 작은 경우 충돌되지 않는다는 문제가 발생했기 때문에 변경했습니다.
OverlapMultiByChannel함수를 사용하여 캐릭터를 중심으로 원 모양으로 충돌을 체크합니다.
첫 번째로 전방 방향 중 가장 가까운 액터와 상호작용 합니다.
두 번째로 전방 방향 중 가장 가까운 액터가 없을 때 오버랩 된 액터 중 가장 가까운 액터와 상호작용 합니다.
이 방법으로 라인 트레이스의 충돌 문제를 해결했고, 플레이어 캐릭터가 액터를 정확하게 바라보지 않아도 상호작용을 할 수 있게 됐습니다.
이로 인해 플레이하는 유저의 입장에서 편의성이 증가할 것을 예상합니다.
=> [Update] 플레이어 캐릭터 상호작용 LineTraceSingleByChannel에서 OverlapMultiByChannel로 변경

Content/Assets/Worm/MI_Worm.uasset, Content/Assets/Worm/M_Worm.uasset, Content/Assets/Worm/SK_Worm.uasset, Content/Assets/Worm/Texture/T_WormC_A.uasset, Content/Assets/Worm/Texture/T_WormC_B.uasset, Content/Assets/Worm/Texture/T_WormE_A.uasset, Content/Assets/Worm/Texture/T_WormE_B.uasset, Content/Assets/Worm/Texture/T_WormN.uasset, Content/Assets/Worm/Texture/T_WormORM.uasset, Content/Assets/Worm/Texture/Worm_BaseColor.uasset, Content/Assets/Worm/Texture/Worm_BaseColor_B.uasset, Content/Assets/Worm/Texture/Worm_Emissive.uasset, Content/Assets/Worm/Texture/Worm_Emissive2.uasset, Content/Assets/Worm/Texture/Worm_Normal.uasset, Content/Assets/Worm/Texture/Worm_OcclusionRoughnessMetallic.uasset, Content/Assets/Worm/lambert2.uasset
기존 텍스쳐와 분리되어있던 머티리얼에 텍스쳐를 적용하였습니다.
머티리얼 인스턴스를 생성하여 적용시켰으며 인스턴스 에디터 상에서 여러 수치를 조절할 수 있습니다.
주요 설정은 다음과 같습니다.
- Diffuse에서 두 텍스쳐를 각각 0과 1의 수치로 전환 가능합니다.
- Emissive에서 등 가시와 목구멍의 밝기를 조정할 수 있습니다.
=> [Update]보스 몬스터 'Worm'의 머티리얼 수정

Content/Blueprints/Actor/Dungeon/BP_DungeonGroundItem.uasset, Source/RogShop/Actor/Dungeon/RSDungeonGroundItem.cpp, Source/RogShop/Actor/Dungeon/RSDungeonGroundItem.h
#109 
데이터 테이블의 RowName을 FName으로 저장하거나 데이터 테이블에 정의된 StaticMesh로 액터를 세팅한다는 점이 ARSInteractableWeapon 클래스와 비슷한 로직을 가진다.
또한, 상호작용을 한다는 점이 같기 때문에 후에 리팩토링 할 경우 공통된 부모를 가지도록 상속 관계를 변경할 예정
후에 인벤토리 구현시 플레이어 캐릭터의 인벤토리로 들어갈 수 있도록 로직을 구현해야합니다..
이때, 인벤토리에 액터를 저장하지 않고, 액터의 FName을 저장하여 UI에서는 데이터 테이블에 접근해서 필요한 변수를 가져와 UI를 세팅할 수 있도록 구현해야합니다.
=> [Add] 몬스터가 죽었을 때 드랍될 아이템 액터 구현

Source/RogShop/Actor/MapGenerator/RSMapGenerator.cpp, Source/RogShop/Actor/MapGenerator/RSMapGenerator.h
[Fixed] 막다른길을 랜덤으로 생성할경우 중간에 길이 끊김을 발생/로직 수정하여 길의 끝에만 막다른길이 생성될수 있도록 수정/경로 확장 함수에 주변에 있는 타일을 인식하여 타일 모양에 변화를 줄 수 있도록 수정/ 만들어 놓은 레벨과 코드에서 사용하는 좌표축이 다름을 확인하여 레벨에 맞게 회전각도 설정
=> [Fixed] 맵생성 로직 수정및 디버깅

Source/RogShop/Actor/Dungeon/RSDungeonGroundItem.h, Source/RogShop/ActorComponent/RSBaseInventoryComponent.cpp, Source/RogShop/ActorComponent/RSBaseInventoryComponent.h, Source/RogShop/ActorComponent/RSDungeonInventoryComponent.cpp, Source/RogShop/ActorComponent/RSDungeonInventoryComponent.h, Source/RogShop/ActorComponent/RSTycoonInventoryComponent.cpp, Source/RogShop/ActorComponent/RSTycoonInventoryComponent.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h, Source/RogShop/RogShop.Build.cs
#32 
플레이어의 인벤토리를 구현한다.
인벤토리의 슬롯은 5개
인벤토리의 슬롯에는 재료 아이템이 들어가게 되며, 같은 재료 아이템을 먹었을 경우 기존에 있던 슬롯에서 개수가 증가하도록 구현했습니다.
재료 아이템을 버릴 수 있습니다.
인벤토리에 들어있는 아이템을 제거하는 함수도 구현했습니다.
인벤토리 클래스는 컴포넌트로 구현했습니다.
타이쿤에서 김영웅님이 준비해준 인벤토리 컴포넌트를 기반으로 상속 관계를 구현해서 타이쿤과 던전 인벤토리를 분리하여 구현했습니다.
UI는 구현되지 않은 상태입니다.
=> [Add] 던전 플레이어 캐릭터의 재료 인벤토리 구현

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/CheatManager/RSCheatManager.cpp, Source/RogShop/Controller/RSDunPlayerController.cpp, Source/RogShop/Controller/RSDunPlayerController.h, Source/RogShop/Object/Relic/RSPlayerStatRelicEffect.cpp, Source/RogShop/Widget/DunShop/DunItemWidget.cpp
플레이어 컨트롤러에서 UI에 대해 접근 제어자를 변경하고 UPROPERTY의 값을 변경해주었습니다.
이벤트 디스패처를 위해 델리게이트 변수를 추가해주었습니다.
해당 델리게이트는 UI의 갱신 시점에 바인딩된 함수를 호출합니다.
무기 슬롯의 데이터를 관리하는 컴포넌트에서 무기를 교체한 경우 델리게이트에 바인딩 된 함수를 호출합니다.
호출할 때 다음 값을 매개변수로 넘겨줍니다.
- 교체된 슬롯의 인덱스
- 데이터테이블에서 무기의 RowName
컴포넌트에서 무기 장착이 제대로 되지 않는 버그를 수정했습니다.
=> [Update] 던전 메인 UI의 슬롯 부분이 갱신 될 수 있도록 컨트롤러와 컴포넌트 수정

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp
인덱스 값이 음수가 될 수 있으므로, unsigned를 사용하지 않도록 변경했습니다.
=> [Bugfix] 슬롯의 인덱스 캐스팅에 자료형 변경

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp
조건문에 의해 특정 무기 슬롯이 nullptr일 경우 UI가 갱신되지 않았는데, 해당 조건문 안에 로직을 집어넣어 UI가 갱신되도록 구현했습니다.
=> [Update] 무기 슬롯이 nullptr일 경우에도 UI가 갱신되도록 구현

Source/RogShop/Character/RSDunBaseCharacter.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h, Source/RogShop/Controller/RSDunPlayerController.cpp, Source/RogShop/Controller/RSDunPlayerController.h, Source/RogShop/Object/Relic/RSPlayerStatRelicEffect.cpp, Source/RogShop/Widget/DunShop/DunItemWidget.cpp
- #89 
- 플레이어의 체력 또는 최대 체력이 갱신될 때 플레이어 측에서 던전 메인 UI를 갱신할 수 있도록 로직 변경
- 플레이어 컨트롤러에 델리게이트 등록 후 플레이어가 해당 델리게이트를 사용하는 방식
- 기존에 수동으로 UI 업데이트 하는 부분 제거
=> [Update] 플레이어 체력 또는 최대 체력 변경시 자동으로 던전 메인 UI 갱신될 수 있도록 수정

Content/Assets/AdventurersKit/BodyA/Armor_01/SKM_BodyA_Armor_01.uasset, Content/Assets/AdventurersKit/BodyA/Armor_01/SK_BodyA_Armor_01.uasset, Content/Blueprints/Characters/BP_DunPlayerCharacter.uasset, RogShop.uproject, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h, Source/RogShop/RogShop.Build.cs
- SkeletalMerging 플러그인 및 모듈 적용
플레이어 캐릭터에 FSkeletalMeshMergeParams 변수 추가
블루프린트 클래스에서 FSkeletalMeshMergeParams의 변수에 적용할 스켈레탈 메시와 본을 추가한다.
C++의 BeginPlay에서 USkeletalMergingLibrary::MergeMeshes함수를 호출하여 머지된 스켈레탈 메시를 생성하여 플레이어 캐릭터 메시에 적용한다.
=> [Add] 모듈식 캐릭터 메시 적용

Source/RogShop/Controller/RSDunPlayerController.cpp, Source/RogShop/Widget/MainMenu/MainMenuWidget.cpp
메인메뉴에서 거점으로 이동 할 때, 버튼의 클릭 이벤트를 사용합니다.
해당 이벤트에 바인딩 된 함수에서는 `UGameplayStatics::OpenLevel`을 사용합니다.
이동할 레벨 이름은 매직 스트링으로 하드 코딩 된 상태입니다.
레벨을 이동할 경우 마우스 커서를 안보이도록 하고, 입력 모드를 게임 온리로 변경합니다.
=> [Update] 메인메뉴에서 거점으로 이동되도록 수정

Source/.editorconfig
.editorconfig 파일을 생성하여 utf-8이 되도록 설정했습니다.
.editorconfig 파일은 프로젝트 폴더의 Source 폴더에 위치합니다.
=> [Add] 비주얼 스튜디오 기본 인코딩 설정 변경

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundIngredient.cpp, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.cpp, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h
땅에 떨어진 재료 아이템을 상호작용할 경우 인벤토리에 추가되도록 구현했습니다.
실행 로직은 다음과 같습니다.
플레이어 캐릭터에 존재하는 액터 컴포넌트를 Get함수를 통해 가져옵니다.
해당 액터 컴포넌트를 참조하여 아이템을 추가하는 AddItem함수를 호출하여 값을 추가합니다.
그 후 자기 자신은 Destory()함수를 호출하여 제거합니다.
액터 컴포넌트는 URSDungeonIngredientInventoryComponent입니다.
기존 인벤토리 컴포넌트의 클래스 이름을 변경했습니다.
URSDungeonInventoryComponent -> URSDungeonIngredientInventoryComponent
=> [Update] 땅에 떨어진 재료 아이템과 상호작용시 인벤토리에 추가되도록 구현

Content/Assets/AdventurersKit/BodyA/Armor_01/SK_BodyA_Armor_01.uasset
변경된 플레이어 캐릭터 메시에는 기존 본과 다른 스켈레탈 본을 사용하기 때문에 무기 착용 부위를 의미하는 소켓이 존재하지 않는다는 문제가 있습니다.
기존 본과 같은 본 및 이름으로 소켓을 추가하고, 같은 트랜스폼을 가지도록 해주었습니다.
타겟이 되는 본 이름은 Hand_r 이며, 소켓 이름은 Weapon_Hand_r 입니다.
=> [Fix] 변경된 플레이어 캐릭터 메시에 소켓 추가

Content/Datas/MonsterSpawnGroupDataTable.uasset, Source/RogShop/DataTable/MonsterSpawnGroupData.cpp, Source/RogShop/DataTable/MonsterSpawnGroupData.h
몬스터를 스폰시킬 때 어떤 몬스터를 얼마나 스폰할지 의미하는 데이터테이블을 추가했습니다.
몬스터의 종류가 다양할 수 있으므로, TArray를 사용해주었습니다.
몬스터의 종류는 FName으로 값을 저장하며, 몬스터 데이터 테이블에서 RowName을 위한 키값으로 사용됩니다.
몬스터의 수는 몬스터를 스폰시킬 때 몇 마리 스폰시킬지를 의미합니다.
=> [Add] 몬스터 스폰 그룹 데이터 테이블 추가

Content/Datas/MonsterConfigDataTable.uasset, Content/Datas/MonsterSkillDataTable.uasset, Content/Datas/MonsterStatDataTable.uasset, Source/RogShop/Character/RSDunMonsterCharacter.h, Source/RogShop/DataTable/MonsterConfigData.cpp, Source/RogShop/DataTable/MonsterConfigData.h, Source/RogShop/DataTable/MonsterSkillData.cpp, Source/RogShop/DataTable/MonsterSkillData.h, Source/RogShop/DataTable/MonsterStatData.cpp, Source/RogShop/DataTable/MonsterStatData.h
- #194 
- 기본적으로 MonsterStatDataTable, MonsterSkillDataTable, MonsterConfigDataTable로 나누었습니다.
- MonsterStatDataTable에서는 몬스터의 스탯(MaxHP, MoveSpeed, AttackPower, AttackSpeed)을 결정합니다.
- MonsterSkillDataTable에서는 몬스터의 스킬(BaseAttackAnimMontage, SkillAnimMontage 등)을 결정합니다.
ㄴ 스킬은 일단 공격 스킬만 넣는 걸로 생각 중이며, 그래서 트레이스 관련 변수도 다 여기에 들어갑니다.
- MonsterConfigDataTable에서는 몬스터의 기타:남는 것들 설정(DeathAnimMontage 등)을 결정합니다.
ㄴ DeathAnimMontage가 스킬이 아닌 이유는 죽음은 공격 스킬이 아니기 때문입니다.
ㄴ 그리고 트레이스 관련 변수에 null이 들어가서 쓸데없는 공간을 차지하게 될 것입니다.
**왜 데이터 테이블을 하나로 만들지 않고 3개로 나누었냐면 
몬스터의 스탯, 스킬, 설정(애니메이션/트레이스 등)은 성격이 명확히 다른 데이터이므로, 
데이터 테이블을 기능별로 분리하여 책임을 나눴습니다.
이를 통해 유지보수성과 확장성이 향상되며, 한 테이블 변경이 전체 로직에 영향을 주는 리스크를 줄일 수 있습니다.**
---
<html>
<body>
<h2>몬스터 관련 정보를 데이터 테이블로 관리하면 좋은 점</h2>
<p>여기 아래에서 말하는 값은 각 몬스터마다 달라야 하는 고유한 체력, 공격력, 스킬, 죽음 애니메이션 …
=> [Add] 몬스터 스탯, 스킬, 설정 데이터 테이블 생성 및 각 테이블의 TableRow에 필요한 변수들 기본적인 거 추가

Config/DefaultGame.ini, Content/Datas/ForestMonsterSpawnGroupDataTable.uasset, Content/Datas/MonsterSpawnGroupDataTable.uasset, Source/RogShop/GameInstanceSubsystem/RSDataSubsystem.cpp, Source/RogShop/GameInstanceSubsystem/RSDataSubsystem.h, Source/RogShop/RSDataSubsystemSettings.h
숲 몬스터 스폰 그룹 데이터 테이블을 생성하고 서브시스템에 등록해주었습니다.
후에 다른 맵의 몬스터 스폰 그룹을 추가할 때 같은 식으로 데이터 테이블 애셋을 생성하고, 서브시스템에 추가로 등록 해주어야합니다.
=> [Add] 숲 데이터 테이블 생성 및 서브시스템 등록

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundRelic.cpp, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundRelic.h, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundWeapon.h, Source/RogShop/Actor/Dungeon/Relic/RSBaseRelic.cpp, Source/RogShop/Actor/Dungeon/Relic/RSBaseRelic.h, Source/RogShop/Actor/Dungeon/Relic/RSStatusRelic.cpp, Source/RogShop/Actor/Dungeon/Relic/RSStatusRelic.h, Source/RogShop/RogShop.Build.cs
유물의 베이스가 되는 클래스 URSBaseRelic 추가
해당 클래스는 ApplyEffect 함수를 가상 함수로 가집니다.
URSBaseRelic 클래스를 상속받아 각 유물의 동작을 구현합니다.
대표적으로 플레이어 캐릭터의 스탯을 변화하는 경우 URSStatusRelic 클래스처럼 구현하도록 합니다.
이 경우 각 스탯별로 클래스를 추가적으로 생성하지 않기 때문에 스탯에 대해서는 URSStatusRelic가 관리합니다.
이렇게 정의된 클래스를 ARSDungeonGroundRelic 클래스에서 상호작용 된 경우
플레이어 캐릭터의 유물 인벤토리에 저장하고, 상호작용 된 유물에 대해서 발동해야하는 동작은 URSBaseRelic 클래스를 상속받은 클래스에 구현된 로직을 실행시킵니다.
=> [Add] 유물 클래스 구현

Content/Datas/ForestMonsterSpawnGroupDataTable.uasset
시범적으로 사용하기 위해 빠르게 스폰될 그룹에 대해 추가했습니다.
숲에서 닭, 염소, 멧돼지, 곰을 소환하기 때문에 이 4가지를 기준으로 7가지 그룹을 생성했습니다.
=> [Update] 숲 몬스터 스폰 그룹 데이터 테이블에 스폰 될 그룹 데이터 추가

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.h, Source/RogShop/Widget/Dungeon/RSInventoryWeaponSlotWidget.cpp, Source/RogShop/Widget/Dungeon/RSPlayerStatusWidget.cpp
무기를 버리는 함수를 추가했습니다.
해당 함수는 UI에서 특정 슬롯을 특정 시간동안 클릭하고 있을 때, 호출됩니다.
무기를 버릴 때 드랍된 액터를 의미하는 ARSDungeonGroundWeapon 클래스를 생성하고 버려지는 무기의 값을 설정해주었습니다.
기존에 장착 중인 무기를 버리는 경우 장착이 해제되도록 했습니다.
기존에 무기를 장착 해제하던 로직을 2곳 이상에서 호출하므로, 함수화 했습니다.
무기를 버릴 때 UI가 갱신되도록 이벤트 디스패처를 호출합니다.
이때, WeaponKey에 빈 값을 넘겨주어 UI를 빈칸으로 만들어줍니다.
=> [Update] 무기를 버리는 기능 추가

Config/DefaultEngine.ini
Pawn 프리셋에서 Camera 채널을 Block에서 Ingnore로 변경하여 카메라 스프링 암에 영향을 주지 않도록 변경했습니다.
=> 폰 콜리전이 카메라 스프링암에 영향을 주지 않도록 수정

Source/RogShop/Actor/Dungeon/Weapon/RSBaseWeapon.cpp, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp
URSPlayerWeaponComponent에서 콜리전을 관리하던 것을 ARSBaseWeapon의 함수가 호출될 때 직접 관리하도록 변경
=> [bugFix] 무기를 장착만 해도 오버랩 이벤트가 발생하던 현상 수정

Content/Datas/IngredientDataTable.uasset
RowName이 1, 2, 3... 의 숫자로 이루어 진것을 아이템 이름과 유사하게  변경
=> [Fix] 재료 데이터 테이블의 RowName 변경

Content/Blueprints/Actor/Dungeon/BP_BossRoomPortal.uasset, Source/RogShop/Actor/Dungeon/RSDunBossRoomPortal.cpp, Source/RogShop/Actor/Dungeon/RSDunBossRoomPortal.h, Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.h
상호작용할 경우 보스방으로 이동할 수 있는 액터 클래스를 구현했습니다.
기존의 상호작용 인터페이스를 사용했습니다.
해당 엑터에 SetTargetTransform함수를 사용하여 이동할 위치를 미리 설정해주어야합니다.
미리 설정할 위치는 보스방에서 플레이어의 위치를 의미할 TargetPoint의 위치를 가져와서 설정해주어야합니다.
상호작용시 Setlocation함수를 호출하여 설정된 TargetTransform으로 이동합니다.
게임모드에서 사용하는 RSSpawnManager에서 해당 액터를 스폰하도록 구현해야합니다.
스폰 위치는 스테이지의 특정 칸에서 보스방으로 이동하는 액터를 스폰합니다.
=> [Add] 보스방으로 이동하는 액터 추가

Content/Blueprints/Actor/Dungeon/BP_WeaponSpawnPadActor.uasset, Content/Maps/BaseAreaMap.umap, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundWeapon.cpp, Source/RogShop/Actor/Dungeon/Weapon/RSWeaponSpawnPadActor.cpp, Source/RogShop/Actor/Dungeon/Weapon/RSWeaponSpawnPadActor.h, Source/RogShop/Controller/RSDunPlayerController.h, Source/RogShop/GameModeBase/RSBaseAreaGameModeBase.cpp, Source/RogShop/GameModeBase/RSBaseAreaGameModeBase.h
1. 한 개의 발판에서 3개의 무기를 스폰하던 로직을 1개만 정중앙에 스폰될 수 있도록 변경, 해당 발판을 맵에 3개 설치해둔 상태
2. 각 한 개의 발판들이 서로가 중복 무기를 생성하지 않도록 로직 수정
3. 3개의 무기 발판중 한 개의 무기를 획득하는 순간 나머지 2개의 발판 위에 있는 무기가 사라질 수 있도록 구현
- ARSDungeonGroundWeapon에서 Interact시 ARSDunPlayerController에 있는 OnFirstWeaponPickUp 변수를 이용하여 브로드캐스트로 알림, ARSBaseAreaGameModeBase에서 받아서 처리
4. 던전 입장 전 무기를 획득했는지의 여부를 ARSBaseAreaGameModeBase에서 bool 변수를 통해 확인할 수 있도록 해당 값을 반환하는 GetIsEquipWeapon 함수 추가
=> [Update] 던전 입장전 3개의 무기 스폰 로직 변경 및 내용 추가

Source/RogShop/Actor/Dungeon/Relic/RSStatusRelic.cpp
기존 로직은 값으로 이동속도를 Set합니다.
이 경우 이동속도가 기존 이동속도에 + 혹은 -되는 로직을 구현하기 힘들어지므로, 기존 이동속도에 값을 추가하거나 줄일 수 있도록 변경했습니다.
=> [Fix] 이동속도 유물 로직 수정

Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.cpp, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.h, Source/RogShop/SaveGame/Dungeon/RSDungeonIngredientSaveGame.cpp, Source/RogShop/SaveGame/Dungeon/RSDungeonIngredientSaveGame.h
플레이어의 재료 인벤토리에서 재료 목록을 저장합니다.
기존 인벤토리에서 배열로 아이템 정보를 저장하던 것을 똑같은 자료구조로 저장하도록 구현했습니다.
기존 세이브와 동일하게 특정 델리게이트에 바인딩하여 해당 델리게이트가 브로드캐스트 할 때 세이브합니다.
로드또한 기존 로드와 동일하게 BeginPlay에서 작동합니다.
=> [Update] 재료인벤토리 세이브 및 로드 구현

Content/Blueprints/Actor/Dungeon/BP_WeaponSpawnPadActor.uasset
- 기존에 PadMesh에 입혀져 있던 큐브 메시 그대로 적용
- 해당 발판을 기준으로 재테스트 필요, 로컬에선 정상 동작
=> [Fix]  제거된 PadMesh 대신 새로 생긴 MeshComp 변수에 큐브 메시 추가

Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.h, Source/RogShop/ActorComponent/RSRelicInventoryComponent.cpp, Source/RogShop/ActorComponent/RSRelicInventoryComponent.h, Source/RogShop/SaveGame/Dungeon/RSDungeonRelicSaveGame.cpp, Source/RogShop/SaveGame/Dungeon/RSDungeonRelicSaveGame.h
플레이어의 유물 인벤토리에서 유물 목록을 저장합니다.
기존 인벤토리에서 배열로 유물 정보를 저장하던 것을 똑같은 자료구조로 저장하도록 구현했습니다.
TArray<FName>으로 저장합니다.
기존 세이브와 동일하게 특정 델리게이트에 바인딩하여 해당 델리게이트가 브로드캐스트 할 때 세이브합니다.
로드또한 기존 로드와 동일하게 BeginPlay에서 작동합니다.
=> [Update] 유물 인벤토리의 세이브, 로드 기능 구현

Source/RogShop/Character/RSDunBaseCharacter.cpp, Source/RogShop/Character/RSDunBaseCharacter.h, Source/RogShop/Character/RSDunMonsterCharacter.cpp, Source/RogShop/Character/RSDunMonsterCharacter.h
델리게이트를 사용해 몬스터가 사망했음을 의미하는 이벤트를 생성합니다.
해당 이벤트에 바인딩 될 함수를 구현해주어 재료 아이템을 드랍하도록 해주었습니다.
재료 아이템을 드랍하기 위해서 몬스터 데이터 테이블에서 드랍할 아이템을 찾고, 재료 데이터 테이블의 데이터로 드랍될 재료 액터를 정의합니다.
후에 확률적으로 드랍되도록 변경해주어야 합니다.
던전 재화 또한 드랍되도록 해주어야합니다.
=> [Update] 몬스터 사망 시 재료 아이템을 드랍하도록 구현

Source/RogShop/Widget/DunShop/RSDunShopWidget.cpp
- 캐릭터가 이동중인 상태에서 던전 상점 오픈시 키 입력 상태를 초기화 시켜서 멈출 수 있도록 수정
=> [Fix] 이동중일때 상점 오픈시 캐릭터가 멈추지 않는 현상 수정

Source/RogShop/BehaviorTree/Tycoon/Task/BTT_RSWaiterMoveCookingTile.cpp
const static을 static const으로 수정 C++의 기본 문법에서는 같은 의미이지만, 언리얼 엔진에서는 빌드에 문제가 생겨 수정했습니다.
=> [BugFix] static 수정

Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/CheatManager/RSCheatManager.cpp, Source/RogShop/CheatManager/RSCheatManager.h, Source/RogShop/GameInstance/RSGameInstance.cpp, Source/RogShop/GameInstance/RSGameInstance.h, Source/RogShop/UtilDefine.h
1. RSGameInstance 내부에 로그 출력을 제어할 수 있는 bool 변수 추가 (기본값 false, true일때 각종 로그 출력 가능)
2. CheatManager에 ToggleDebugLog 함수 등록, 게임 내 콘솔창에서 해당 함수로 로그 출력 제어 bool 변수 Toggle 가능
3. 모든 로그 출력 부분을 로그 출력 제어 변수값을 이용해서 if문으로 처리하면 너무 복잡할 것 같아서 UtilDefine 파일 내부에 로그 출력 제어 변수값을 이용하여 해당 값이 true 일때만 로그를 찍을 수 있는 매크로 함수 추가
-  해당 함수를 이용하여 캐릭터 주변 디버그 라인 제어 및 일부 함수 내부 로그 출력 부분 리팩토링
- 기존에 사용했었던 매크로 함수들 전부 로그 출력 제어 변수를 이용하여 로그 출력이 제어될 수 있도록 변경 예정
=> [Add] GameInstance 로그 제어 bool 변수값에 따른 각종 로그 출력 제어 로직 일부 추가

Content/Blueprints/AL_Blueprints.uasset, Content/Blueprints/Actor/Dungeon/BP_KnightBattleaxe.uasset, Content/Blueprints/Actor/Dungeon/Weapon/BP_KnightBattleaxe.uasset, Content/Datas/DungeonObjectDataTable.uasset, Content/Datas/WeaponClassDataTable.uasset, Source/RogShop/DataTable/DungeonObjectData.cpp, Source/RogShop/DataTable/DungeonObjectData.h, Source/RogShop/GameInstanceSubsystem/RSDataSubsystem.cpp, Source/RogShop/GameInstanceSubsystem/RSDataSubsystem.h, Source/RogShop/RSDataSubsystemSettings.h
던전에서 스폰할 액터에 대한 클래스를 데이터테이블로 관리하도록 데이터 테이블 생성
=> [Add] 던전 오브젝트 데이터 테이블 생성

Content/Blueprints/Widgets/Dungeon/WBP_InventorySlot.uasset, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundIngredient.cpp, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundIngredient.h, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.cpp, Source/RogShop/Character/RSDunMonsterCharacter.cpp, Source/RogShop/Widget/Dungeon/RSIngredientInventoryWidget.cpp, Source/RogShop/Widget/Dungeon/RSIngredientInventoryWidget.h, Source/RogShop/Widget/Dungeon/RSInventorySlotWidget.cpp, Source/RogShop/Widget/Dungeon/RSInventorySlotWidget.h
URSInventorySlotWidget에서 마우스 클릭 입력은 버튼으로 수행하도록 변경
해당 슬롯을 클릭했을 때 바인딩된 함수로 저장된 데이터 테이블 키를 반환하도록 구현
재료 인벤토리에서 슬롯이 클릭된 경우 클릭된 슬롯의 아이템이 드랍되도록 구현
플로우는 다음과 같습니다.
슬롯 위젯의 클릭 이벤트(저장된 데이터 테이블 키 반환) -> 클릭된 슬롯의 아이템 키 값 저장 ->재료 인벤토리에서 타이머 시작 -> 타이머 완료 -> 저장됐던 아이템 키 값을 기준으로 아이템 드랍 -> UI 갱신
=> [Update] 재료 인벤토리의 아이템 드랍 기능 수정

Source/RogShop/DataTable/ItemInfoData.h, Source/RogShop/Widget/DunShop/RSDunItemWidget.cpp, Source/RogShop/Widget/Dungeon/RSInventorySlotWidget.cpp, Source/RogShop/Widget/Dungeon/RSInventorySlotWidget.h, Source/RogShop/Widget/Dungeon/RSPlayerStatusWidget.cpp, Source/RogShop/Widget/Dungeon/RSWeaponInventoryWidget.cpp
- 머티리얼 인스턴스 추가 할당을 위하여 기존 UTexture2D 대신에 UObject 타입을 변수에 할당할 수 있도록 변경
- AllowedClasses에 원하는 할당 타입 추가 가능, 현재는 Texture2D, MaterialInstance만 할당 가능하도록 선언해둔 상태
- 각 Texture2D, MaterialInstance 할당 후 해당 데이터 정상 출력되는지 전부 확인 완료
=> [Update] ItemInfoData 내부 ItemIcon 타입 UObject 사용할 수 있도록 변경

Content/Blueprints/Widgets/Dungeon/WBP_SendIngredient.uasset, Source/RogShop/Actor/RSInteractableLevelTravel.cpp, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.cpp, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.h, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/ActorComponent/RSRelicInventoryComponent.cpp, Source/RogShop/ActorComponent/RSRelicInventoryComponent.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h, Source/RogShop/GameInstanceSubsystem/RSSaveGameSubsystem.cpp, Source/RogShop/GameInstanceSubsystem/RSSaveGameSubsystem.h, Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp, Source/RogShop/GameModeBase/RSDungeonGameModeBase.h, Source/RogShop/Widget/Dungeon/RSSendIngredientWidget.cpp
보스를 잡고 스테이지 이동이 가능하도록 던전에 대한 데이터를 저장 및 로드하도록 구현
재료, 유물의 잘못된 로드 로직 수정
세이브 시점을 의미하는 델리게이트를 플레이어 캐릭터에서 게임 인스턴스 서브시스템을 생성하여 해당 서브시스템으로 옮겨주었습니다.
그에 따라 기존에 바인딩 하던 로직에 수정을 주었습니다.
보스 잡고 재료를 보내는 UI에서 확인 버튼을 누를 경우 다음 스테이지로 이동되도록 해주었습니다.
=> [Update] 보스 잡고 스테이지 이동이 가능하도록 수정

Content/Assets/CasualSet01/BodyA/Material/MI_ChefCloth.uasset, Content/Assets/CasualSet01/BodyA/Material/M_Chef_Apron.uasset, Content/Assets/CasualSet01/BodyA/Material/M_Chef_Casual_01_Base1.uasset, Content/Assets/CasualSet01/BodyA/Material__28.uasset, Content/Assets/CasualSet01/BodyA/SKM_Apron.uasset, Content/Assets/CasualSet01/BodyA/SKM_ApronPhysics.uasset, Content/Assets/CasualSet01/BodyA/SKM_Apron_DefaultMaterial_BaseColor.uasset, Content/Assets/CasualSet01/BodyA/SKM_Apron_Skeleton.uasset, Content/Assets/CasualSet01/BodyA/Textures/SKM_Apron_DefaultMaterial_BaseColor.uasset, Content/Assets/CasualSet01/BodyA/Textures/SKM_Apron_DefaultMaterial_Normal.uasset, Content/Assets/CasualSet01/BodyA/Textures/SKM_Apron_DefaultMaterial_OcclusionRoughnessMetallic.uasset, Content/Assets/CasualSet01/BodyA/Textures/T_Chef_Casual_01_BaseColor.uasset, Content/Assets/CasualSet01/BodyB/Materials/MI_BodyB_Casual_Waitress.uasset, Content/Assets/StylizedCharacters/BodyA/Body/Materials/MI_BodyA_Chef.uasset, Content/Assets/StylizedCharacters/BodyA/Body/SK_BodyA.uasset, Content/Assets/StylizedCharacters/BodyA/Eyes/Eyes_01/MI_Eyes_Chef.uasset, Content/Assets/StylizedCharacters/BodyA/Eyes/Eyes_01/MI_Eyes_Waitress.uasset, Content/Assets/StylizedCharacters/BodyA/Hairstyles/Hairstyle_02/Materials/MI_Hairstyle_Waitress.uasset, Content/Assets/StylizedCharacters/BodyA/Heads/Head_01/Materials/MI_HeadA_Chef.uasset, Content/Assets/StylizedCharacters/BodyA/Mustaches/Mustache_01/Materials/MI_MustacheA_Chef.uasset, Content/Assets/StylizedCharacters/BodyB/Eyebrows/Eyebrows_01/Materials/MI_EyebrowsB_Waitress.uasset, Content/Assets/StylizedCharacters/BodyB/Heads/Head_01/Materials/MI_HeadB_Waitress.uasset, Content/Blueprints/Characters/Tycoon/BP_RSTycoonChefCharacter.uasset, Content/Blueprints/Characters/Tycoon/BP_RSTycoonWaiterCharacter.uasset
기존 캐릭터를 활용한 셰프와 웨이트리스의 애셋과 머티리얼 등을 추가하고 해당 블루프린트에 적용하였습니다.
- 머티리얼을 기존 캐릭터와 분리생성하였습니다. 
- 셰프의 경우 앞치마 콜리전 무시 문제가 있습니다.
- 애셋 사용은 가능하기에 일단 적용 후, 앞치마는 추후 해결할 예정입니다.
=> [Add] 셰프와 웨이트리스 캐릭터 애셋 추가 및 블루프린트에 애셋 적용

Source/RogShop/Widget/Dungeon/RSSendIngredientWidget.cpp
URSTycoonSaveGame에 구현한 함수가 URSSaveGameSubsystem으로 옮겨가면서 생긴 버그 수정
URSSaveGameSubsystem의 포인터를 Get하여 함수를 호출하도록 변경
=> [Fix] 던전에서 타이쿤으로 재료 보내는 로직 수정

Source/RogShop/Widget/InGame/RSInGameMenuWidget.cpp
[Fixed] InGameUI에서 닫기버튼 클릭시 포커스 오류나는 문제 수정
=> [Fixed] InGameUI에서 닫기버튼 클릭시 포커스 오류나는 문제 수정

Source/RogShop/GameInstanceSubsystem/RSSaveGameSubsystem.cpp, Source/RogShop/GameInstanceSubsystem/RSSaveGameSubsystem.h, Source/RogShop/Widget/MainMenu/MainMenuWidget.cpp
URSSaveGameSubsystem에서 던전에서 사용하는 세이브 파일들이 존재하는지 확인하고 제거하는 함수를 추가해주었습니다.\
이외에 모든 세이브 파일들이 존재하는지 확인하고 제거하는 함수를 추가해주었습니다,
UMainMenuWidget에서 새 게임 버튼을 클릭 했을 때 모든 세이브 파일들이 존재하는지 확인하고 제거해줍니다.
불러오기 버튼을 클릭했을 경우 던전 세이브 파일만 제거되도록 구현해주었습니다.
=> [Update] 새 게임 클릭시 던전 세이브 파일이 제거되도록 구현

Source/RogShop/GameInstanceSubsystem/RSSaveGameSubsystem.cpp, Source/RogShop/GameInstanceSubsystem/RSSaveGameSubsystem.h, Source/RogShop/Widget/MainMenu/MainMenuWidget.cpp
기존 조건식에서는 던전에 대한 세이브 파일이 존재하는 경우에만 불러오기 버튼이 나타나도록 돼있었습니다.
타이쿤의 세이브 파일이 존재하는 경우에도 불러오기 버튼이 나타나도록 수정해주었습니다.
=> [Bugfix] 불러오기 버튼을 숨겨야할지에 대한 잘못된 조건문 수정

Content/Blueprints/Characters/BP_DunUndeadHoundCharacter.uasset
<해결 방법>
- 캡슐 컴포넌트 크기를 발에 맞게 조정
- 하운드 BP의 부모클래스를 RSDunMonsterBase로 변경
+ 하운드가 공격할때 플레이어 몸을 뚫고 공격 애니메이션이 나오길래 캡슐 컴포넌트를 앞쪽에 키워서 좀 완화했습니다.
=> [Bugfix] 하운드가 안 움직이는 버그 해결

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.cpp, Source/RogShop/Widget/Dungeon/RSPlayerInventoryWidget.cpp, Source/RogShop/Widget/InGame/RSInGameMenuWidget.cpp
라이프 에센스에서 타이머가 자신의 액터가 사라져도 계속 반복 동작하던 문제가 있어서 특정 상황에서는 ClearTimer을 통해 타이머가 더이상 동작하지 않도록 해주었습니다.
위젯이 제대로 전환되지 않던 문제는 위젯을 닫거나 전환 할 때 단순하게 뷰포트에 제거만 했기 때문에 발생한 문제입니다.
해당 문제는 플레이어 컨트롤러를 참조하여 위젯을 전환하는 함수를 호출하여 해결해주었습니다.
=> [bugFix] 라이프 에센스 액터의 에러 수정 및 위젯이 제대로 전환되지 않던 문제 해결

Content/Blueprints/Controllers/BP_DunPlayerController.uasset, Content/Blueprints/Widgets/Dungeon/WBP_LoadingWidget.uasset, Content/Blueprints/Widgets/InGame/WBP_LoadingUIWidget.uasset, Source/RogShop/Controller/RSDunPlayerController.cpp, Source/RogShop/Controller/RSDunPlayerController.h, Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp, Source/RogShop/GameModeBase/RSDungeonGameModeBase.h, Source/RogShop/Widget/Dungeon/RSLoadingWidget.cpp, Source/RogShop/Widget/Dungeon/RSLoadingWidget.h
거점 게임모드에서는 특정 델리게이트가 존재하지 않아 로딩이 완료된 시점을 의미하는 이벤트를 호출할 수 없다는 문제가 있었습니다.
이로 인해서 로딩창이 생성된 후 사라지지 못했습니다.
이 문제를 해결하기 위해서 플레이어 컨트롤러에서는 게임모드가 던전 게임모드일 경우에만 로딩창을 생성하도록 해주었습니다.
로딩 위젯에서 C++클래스를 사용하지 않은 상태였는데, C++클래스를 생성해주었습니다.
위젯의 NativeConstruct에서 던전 게임모드의 델리게이트에 로딩 위젯을 사라지게하는 함수를 바인딩 해주었습니다.
게임모드에서 모든 로딩이 완료됨을 의미하는 델리게이트를 추가해주고 던전의 모든 스폰 로직이 마무리 된 후 브로드캐스트 해주도록 했습니다.
=> [Fix] 거점에서 로딩창이 계속 남아있는 문제 수정

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.cpp, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.h
기존 로직은 타이머와 람다함수를 사용해주었는데 Destory함수 호출 시 패키징에서는 프로그램이 터지는 문제가 발생했습니다.
로직을 수정할 겸 자연스러운 액터 이동을 위해서 Tick함수를 사용해주었습니다.
비용은 타이머보다 높지만 자연스러운 움직임이 가능하기 때문에 Tick을 선택했습니다.
처음에는 재화가 땅에 떨어지도록 해주었고, 바닥에서부터 플레이어 캐릭터를 추적하도록 설정해주었습니다.
추적 중에는 점점 추적 속도가 빨라집니다.
획득되는 시점은 플레이어 캐릭터의 캡슐 컴포넌트에 대한 반지름 값을 기준으로 반지름 값보다 가까운 경우 획득 처리가 되도록 해주었습니다.
=> [Bugfix] 기존 로직이 패키징에서 동작하지 않아 로직 수정

Content/Assets/PlayerAnimations/Rolling_Montage.uasset, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/AnimNotifyState/RSAttackAnimNotifyState.cpp, Source/RogShop/AnimNotifyState/RSAttackBufferAnimNotifyState.cpp, Source/RogShop/AnimNotifyState/RSBlockMontageSkipAnimNotifyState.cpp, Source/RogShop/AnimNotifyState/RSBlockMontageSkipAnimNotifyState.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h
몽타주의 재생을 멈추고 시퀀스가 재생되도록 하거나 다른 몽타주가 재생되게하는 스킵 기능을 추가해주었습니다.
기존 몽타주 재생 중 멈추고 다른 몽타주를 재생할 때, 몽타주 재생 중의 상태가 관리되지 않는 문제가 있었습니다.
이 문제는 기존 몽타주에서 노티파이나 노티파이 스테이트가 제대로 호출되지 않고 넘어가버리기 때문에 발생하는 문제였습니다.
현재 상태에 대한 관리는 노티파이 스테이트에서 이루어지기 때문에, 호출되지 않은 노티파이 스테이트를 직접 호출해주어 상태가 관리되도록 구현해주었습니다.
현재 플레이어가 스킵이 가능한 상태인지 값을 저장하는 변수를 추가해주었고, 해당 값은 노티파이 스테이트를 사용하여 몽타주의 특정 구간에서는 스킵이 불가능하도록 해주었습니다.
현재 해당 기능은 구르기에만 적용을 해두었기 때문에 추후 다른 애니메이션 몽타주들에도 적용해야합니다.
=> [Add] 몽타주 스킵 기능 추가

Content/Assets/PlayerAnimations/equip.uasset, Content/Assets/PlayerAnimations/equip_Montage.uasset, Content/Blueprints/AnimInstance/ABP_DunPlayerAnim.uasset, Content/Blueprints/AnimInstance/ABP_SwordDunPlayerAnim.uasset, Content/Blueprints/Characters/BP_DunPlayerCharacter.uasset, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.h, Source/RogShop/AnimNotify/RSWeaponChangeAnimNotify.cpp, Source/RogShop/AnimNotify/RSWeaponChangeAnimNotify.h, Source/RogShop/Character/RSDunPlayerCharacter.cpp
무기 교체 애니메이션 시퀀스 및 몽타주 임포트
플레이어 캐릭터에 무기 교체 애니메이션 몽타주를 참조하도록 변수 추가
플레이어 캐릭터의 애님인스턴스 블루프린트에서 상속받은 인터페이스의 애니메이션 출력에 블렌드 타임 추가
플레이어 캐릭터의 애님인스턴스 블루프린트에서 로코모션 부분들에 애니메이션이 자연스러운 전환이 되도록 inertialization 추가
애니메이션 노티파이를 사용하여 몽타주 재생 중 특정 시점에 무기가 교체되도록 해주었습니다.
이때, 노티파이는 매개변수를 가질 수 없으므로, 무기 컴포넌트에 변경할 무기 슬롯에 대한 부분을 멤버변수로 저장해주어 해결했습니다.
기존 무기 변경 로직을 수정해주었습니다.
=> [Add] 무기 교체 애니메이션 구현

Source/RogShop/Character/RSDunPlayerCharacter.cpp
구르기가 특정 조건에 의해 되지 못해도 캐릭터가 회전하는 문제가 있어서 수정했습니다.
캐릭터를 회전하는 로직이 애니메이션의 재생과 다른 조건식에 위치하여 문제가 됐었는데 이를 수정해주었습니다.
=> [Fix] 구르기가 되지 않아도 회전하는 문제 해결

Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Attack-001_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Attack-002_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Attack-003_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Attack-004_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Damage_Take-001_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Damage_Take-004_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Dead-001_Cue.uasset, Content/Assets/Animal_Monster_Sound_Pack/cues/Harpy_Dead-003_Cue.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_Attack_Front.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_Death.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_RootDeath.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_RootHorizontalAtk.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_RootVertcalAtk.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_Summon.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_ThrowHoney.uasset, Content/Assets/CarnivorousPlant/AnimMontage/AM_ServantFlowerAtk.uasset
- 각 몬스터의 공격 및 죽음 애님 몽타주에 사운드 재생 노티파이를 추가해서 사운드 재생
- 각 적용 사운드에 디폴트 어테뉴에이션 적용
- 보스가 소환하는 작은 꽃의 죽음 몽타주가 없어서 해당 부분은 사운드 안 들어간 상태
기타 사항 : 현재 보스가 소환하는 작은 꽃 일반몹이 데미지를 입지 않음, 확인 필요
=> [Add] 숲 보스 및 보스가 소환하는 일반몹의 공격/죽음 시 사운드 추가

Content/Maps/BaseAreaMap.umap, Content/Maps/BaseAreaMeshes.umap, Content/Maps/LV_SceneRender.umap
거점 레벨에 소속되어있던 서브레벨의 액터를 모두 메인 거점레벨에 옮긴 뒤 서브레벨을 삭제하였습니다.
=> [Update]거점레벨의 서브레벨 액터 > 메인 거점 레벨과 머지 후 서브레벨 삭제

Source/RogShop/Actor/Dungeon/Weapon/RSWeaponSpawnPadActor.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.h, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp
SpawnManager의 무기를 스폰하는 함수에 Impulse를 실행할건지 매개변수를 받고 true일 경우에만 실행되도록 해주었습니다.
현재 거점에서 무기를 스폰하는 경우 매개변수로 false를 넘깁니다.
이외의 경우 모드 true로 넘깁니다.
=> [Fix] 거점에서 무기 스폰할 때 항상 Impulse가 실행되는 문제 해결

Source/RogShop/Actor/Dungeon/RSDunNextStagePortal.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.h, Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp, Source/RogShop/GameModeBase/RSDungeonGameModeBase.h, Source/RogShop/SaveGame/Dungeon/RSDungeonStageSaveGame.h, Source/RogShop/Widget/Dungeon/RSSendIngredientWidget.cpp
위젯에서 스테이지를 이동하기 전에 현재 스테이지가 마지막 스테이지인지 확인하고, 마지막 스테이지인 경우 거점으로 이동되도록 변경해주었습니다.
거점으로 이동할 경우 던전에 대한 세이브파일이 제거되도록 해주었습니다.
보스를 잡고 스폰되는 재료 보내기 및 스테이지 이동 액터가 마지막 스테이지에서 스폰된 경우 상호작용 이름이 "거점으로"가 되도록 수정했습니다.
스테이지별로 보스를 잡고 타이쿤으로 보낼 수 있는 재료의 수를 변경해주었습니다.
=> [Update] 마지막 스테이지 클리어시 거점으로 이동되도록 변경

Content/Blueprints/Widgets/Dungeon/WBP_SendIngredient.uasset, Source/RogShop/Widget/Dungeon/RSSendIngredientWidget.cpp, Source/RogShop/Widget/Dungeon/RSSendIngredientWidget.h
위젯 블루프린트에 경고창 관련한 UI을 추가해주었습니다.
위젯 클래스의 C++에서 경고창을 나타나게 하거나 숨기도록 해주었습니다.
경고창이 나타나는 조건은 타이쿤으로 보낼 재료가 보낼 수 있는 재료의 수보다 적게 선택된 경우입니다.
만약 보낼 수 있는 재료의 수만큼 모두 보낼 재료를 채우면 경고창이 나타나지 않고 즉시 이동합니다.
위의 기능을 위한 변수 및 함수들을 추가했습니다.
=> [update] 보스 잡고 보낼 재료를 적게 선택한 경우 경고창이 나타나도록 구현

Source/RogShop/Character/RSDunPlayerCharacter.cpp, Source/RogShop/Character/RSDunPlayerCharacter.h, Source/RogShop/Widget/Dungeon/RSPlayerStatusWidget.cpp
현재 체력과 최대 체력이 UI에 제대로 표기되지 않는다는 문제가 있었습니다.
해당 문제는 세이브된 데이터가 없거나 불러올 때 UI를 갱신시키지 못하기 때문에 발생한 문제입니다.
세이브 파일이 없는 경우 기본적으로 설정된 값을 기준으로 체력을 변경해주어 UI가 갱신되도록 해주었습니다.
세이브 파일이 있는 경우 저장된 체력값을 기준으로 현재체력을 변경해주었습니다.
현재 최대 체력의 경우에는 세이브하지 않으므로, 기본적으로 설정된 값을 기준으로 최대 체력을 변경합니다.
즉, 기본적으로 설정된 값을 사용한다는 것은 적용된 값 자체는 같아 값에 변화는 없지만 델리게이트를 호출하여 브로드캐스트합니다.
그 결과로 체력에 대한 UI가 갱신되도록 합니다.
=> [Bugfix] 현재 체력과 최대 체력이 제대로 갱신되지 않는 문제 수정

Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp
플레이어 캐릭터가 공격시 무기의 데미지를 Get할 때 잘못된 인덱스 값을 사용하여 문제가 있었습니다.
다시 제대로 된 인덱스 값을 사용하도록 수정해주었습니다.
=> [Fix] 무기 공격력이 재대로 적용되지 않던 문제 수정

Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp, Source/RogShop/Character/RSDunMonsterCharacter.cpp
기존 몬스터와 보스에서 재료 아이템과 재화를 드랍하는 함수를 델리게이트에 바인딩하지 않은 상태였습니다.
몬스터가 죽었음을 의미하는 델리게이트에 관련 함수를 바인딩하여 해결했습니다.
=> [Bugfix] 몬스터와 보스가 재료 아이템 및 재화를 드랍하지 않던 문제 해결

Content/Assets/SwordTrailVFX/VFX/NS_Trail_11.uasset
NS_Trail_11 이펙트에 변수를 추가했습니다.
- User.EffectWidth (float) 변수로 이펙트가 발현되는 범위의 길이를 조절할 수 있습니다. 현재 기본값은 60입니다.
- User.EffectPosition (vector)변수의 Z값으로 이펙트의 중심 위치를 조절할 수 있습니다. 현재 기본값은 55입니다.
=> [Update] VFX 수치 조절 변수 추가

Source/RogShop/Actor/Dungeon/Weapon/RSBaseWeapon.cpp
박스 컴포넌트의 월드 기준 크기 절반을 가져와 Trail의 나이아가가라에 이펙트 반경 값을 Set합니다.
SetFloatParameter함수를 사용하여 User.EffectWidth의 값을 설정합니다.
박스 컴포넌트의 월드 기준 위치에서 Z축 방향으로 절반 크기만큼 아래로 이동한 값을 계산하여 박스의 최하단 중심 위치를 구합니다.
구한 위치를 나이아가라 컴포넌트 기준의 상대 위치로 변환하여 나이아가라 이펙트 내부의 위치값을 변경할 수 있도록 해주었습니다.
SetVectorParameter함수를 사용하여 User.EffectPosition의 값을 설정합니다.
=> [Update] Trail VFX의 크기와 위치 변경

Source/RogShop/Widget/Dungeon/RSMiniMap.cpp
[Fixed] 미니맵에서 보스몬스터 타일이 회전하던 문제 해결
=> [Fixed] 미니맵에서 보스몬스터 타일이 회전하던 문제 해결

Content/Assets/UI/Image/T_DropdownMenu.uasset, Content/Assets/UI/Image/T_HPBarPlayerHead.uasset, Content/Assets/UI/Image/T_HPBarPlayerLine.uasset, Content/Assets/UI/Image/T_HPBarPlayerMarkerL.uasset, Content/Assets/UI/Image/T_HPBarPlayerMarkerS.uasset, Content/Assets/UI/Image/T_HPBarPlayerTail.uasset, Content/Assets/UI/Image/T_SlideCursor.uasset, Content/Assets/UI/Image/T_UIButtonB.uasset, Content/Assets/UI/Image/T_UIIconRange.uasset
플레이어의 체력바 UI 스킨 이미지를 추가하였습니다.
- 헤드와 중간선, 꼬리로 나누어서 확장 가능하도록 하였습니다.
- 눈금은 L과 S 두가지로 제작하였습니다.
- 눈금은 체력바의 중간선과 높이를 맞추어 제작하여 좌우 위치만 조정하면 되도록 하였습니다.
- 컬러는 부분별 마스크는 없지만 조정은 용이하도록 그레이스케일로 제작했습니다.
추가로 크기가 필요이상으로 큰 UI텍스쳐들의 해상도를 조정하였습니다.
=> [Add] 체력바 UI 스킨 이미지 추가 및 UI 텍스쳐 해상도 조정

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp, Source/RogShop/Actor/MapGenerator/RSSpawnManager.h, Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.cpp
재료 아이템을 스폰하는 함수에서 고정적으로 재료 아이템을 1개만 스폰하던 문제가 있었습니다.
스폰할 개수를 매개변수로 받아서 스폰할 때 수량을 정할 수 있도록 해주었습니다.
ARSDungeonGroundLifeEssence의 불필요한 코드를 제거했습니다.
=> [Fix] 아이템 드랍시 1개만 드랍되는 문제 수정

Content/Blueprints/Widgets/Dungeon/WBP_BossInfoWidget.uasset, Content/Blueprints/Widgets/Dungeon/WBP_MonsterHPBarWidget.uasset, Content/Blueprints/Widgets/Dungeon/WBP_PlayerStatusWidget.uasset
- 보스 이하 몬스터 체력바의 2단 감소 효과 이펙트의 위치 일치성을 개선하였습니다.
- 더불어 보스 체력바 위의 보스 이름에 장식 이미지와 폰트 장식을 추가하여 강조하였습니다.
- 무기 슬롯의 번호 폰트를 수정하여 가시성을 향상시켰습니다.
=> [Update] 보스 및 몬스터 체력바 이펙트 비주얼 개선 / 보스 이름 UI 개선 / 무기슬롯 넘버 가시성 개선

Content/Assets/UI/Image/T_HPBarPlayerLine.uasset, Content/Blueprints/Characters/BP_DunPlayerCharacter.uasset, Content/Blueprints/Widgets/Dungeon/WBP_PlayerHPBar.uasset, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.cpp, Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp, Source/RogShop/Widget/Dungeon/RSPlayerHPBarWidget.cpp, Source/RogShop/Widget/Dungeon/RSPlayerHPBarWidget.h
플레이어 캐릭터의 카메라 위치를 z축으로 25만큼 위로 올렸습니다.
체력바를 몬스터와 같이 자연스럽게 감소하게 하여 시각적인 효과를 주었습니다.
해당 과정에서 프로그레스바를 2개로 분리하고, 백그라운드를 별도의 이미지로 분리했습니다.
던전 재화 습득 중 캐릭터가 사라지는 경우 nullptr을 체크하도록 해주었습니다.
=> [Update] 카메라, 체력바, 버그 수정 등 작업

Source/RogShop/Widget/MainMenu/OptionMenuWidget.cpp
세이브된 값이 없을때는 nullptr로 설정해놨던 코드
-> 처음 실행했을때 참조 오류 발생
-> 코드 제거
=> [Fix] nullptr 참조하는 코드 제거

Source/RogShop/Actor/BaseArea/RSGameFlowDisplayActor.cpp, Source/RogShop/Actor/BaseArea/RSGameFlowDisplayActor.h
위젯을 캐싱하여 저장하지 않고, 상호작용시마다 UI를 반복해서 생성되도록 해주었습니다.
자주 생성되거나 반복적으로 보이게될 UI가 아니기 때문에 캐싱하지 않도록 해주었습니다.
=> [Fix] 위젯을 캐싱하지 않도록 변경

Source/RogShop/Character/RSDunPlayerCharacter.cpp
플레이어 캐릭터의 스텟을 초기화하는 Load에서 식당에서 섭취한 음식이 반영되도록 수정해주었습니다.
=> [Update] 식당에서 섭취한 음식이 던전에서 반영되도록 수정

Source/RogShop/Widget/InGame/RSGuideButtonWidget.cpp, Source/RogShop/Widget/InGame/RSGuideButtonWidget.h
- 이미 생성된 위젯을 열고 닫기만 할 경우, NativeConstruct로 바인딩을 하면 중복 바인딩 문제가 생기기 때문에 해당 부분 변경
=> [Fix] 가이드 위젯 중복 바인딩 문제 해결

Source/RogShop/Actor/Dungeon/Altar/RSHPToLifeEssenceAltar.cpp
타이머 델리게이트에서 람다함수를 만들어 사용할 때 this에 대해 암시적으로 this가 캡처되는 경우 빌드에 오류가 발생하기 때문에 해당 코드를 수정해주었습니다.
=> [Fix] this의 암시적 사용 문제 해결

Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp, Source/RogShop/Character/RSDunPlayerCharacter.cpp
스폰 매니저에서 기존 세이브파일을 무시하고 새로 생성한 세이브만 저장하여 기존 세이브 파일이 초기화되는 문제를 해결했습니다.
세이브파일이 이미 존재하는 경우 해당 세이브파일을 로드하고, 기존 값에 갱신을 하도록 수정했습니다.
=> [Fix] 던전의 세이브 파일이 초기화되는 문제 수정

Content/Assets/Characters/Mannequins/Meshes/SK_Mannequin.uasset, Content/Assets/PlayerAnimations/Locomotion/Anim_CK2_Idle_S2_RM.uasset, Content/Assets/PlayerAnimations/Locomotion/Anim_CK3_Idle_S2_RM.uasset, Content/Assets/PlayerAnimations/Weapon/Katana/NormalAttack/Anim_Katana_Attack_Combo2.uasset, Content/Assets/PlayerAnimations/Weapon/Katana/NormalAttack/Anim_Katana_Attack_Combo2_Montage.uasset, Content/Assets/Weapons/Katana/NormalKatana/SKM_SKatana.uasset, Content/Assets/Weapons/Katana/NormalKatana/SK_SKatana.uasset, Content/Assets/Weapons/Katana/NormalKatana/SM_SKatana.uasset, Content/Blueprints/Actor/Dungeon/Weapon/BP_NormalKatana.uasset, Content/Blueprints/AnimInstance/Dungeon/Player/ABP_DunPlayerAnim.uasset
카타나 관련 Idle 애님 두 애셋에 관한 오류를 해결하였습니다.
- 핵심적으로 꼬이는 Root와 Pelvis 본의 전환 간 애니메이션 보간 속도를 극도로 줄였습니다.
- 'FastBottom'이라는 TimeBlendProfile을 새로 생성하고 Idle Inertialization에 추가했습니다.
- 두 본의 시간 모두 0.1로 설정하였습니다.
노멀 카타나의 기본 트랜스폼을 변경하였습니다.
- 다른 무기들과 다른 값을 가진 노멀 카타나 회전값을 수정하였습니다.
- 노멀 카타나가 포함된 블루프린트를 수정하였습니다.
=> [Fix] 카타나 Idle 애니메이션 풋 싱크 해결

Source/RogShop/Actor/Dungeon/Altar/RSHPToLifeEssenceAltar.cpp, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.cpp, Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundLifeEssence.h, Source/RogShop/Actor/Dungeon/TreasureChest/RSLifeEssenceTreasureChest.cpp
타이머 등록 후 액터가 파괴된 경우 타이머가 동작하지 않도록 로직을 수정했습니다.
액터가 파괴될 경우 타이머를 제거하거나 타이머에서 현재 객체의 상태를 확인 후 동작하도록 했습니다.
해당 로직 수정 후 프로그램이 터지지 않는 것을 확인했습니다.
=> [Fix] 타이머 중 액터가 파괴됐을 때 프로그램이 터지는 문제 수정

Source/RogShop/Actor/Dungeon/Altar/RSHPToLifeEssenceAltar.cpp, Source/RogShop/Actor/Dungeon/TreasureChest/RSLifeEssenceTreasureChest.cpp
재단에서 생명의 정수가 1개씩 적게 되는 문제를 해결해주었습니다.
반복문의 조건식이 잘못 된 상태였습니다.
재단과 상호작용할 경우 생명의 정수가 플레이어 캐릭터 기준으로 스폰되도록 수정했습니다.
=> [Fix] 재단에서 생명의 정수가 1개씩 적게 되는 현상 수정

Source/RogShop/GameModeBase/RSTycoonGameModeBase.cpp, Source/RogShop/Widget/Tycoon/RSTycoonFoodListWidget.h
FoodList 열면 UPROPERTY() 처리가 안되있어 GC가 수거해가서 생기던 문제 해결
=> [Fix] FoodList열면 게임이 터지던 버그 수정
