Content/Blueprints/Characters/BP_DunPlayerCharacter.uasset
RogShop.uproject
Source/RogShop/Character/ARSDunMonsterCharacter.cpp
Source/RogShop/Character/ARSDunMonsterCharacter.h
Source/RogShop/Character/RSDunBaseCharacter.cpp
Source/RogShop/Character/RSDunBaseCharacter.h
Source/RogShop/Character/RSDunPlayerCharacter.cpp
Source/RogShop/Character/RSDunPlayerCharacter.h
Source/RogShop/RogShop.Build.cs

- #5
던전 캐릭터 들을 위한 베이스 클래스를 생성
- ARSDunBaseCharacter
베이스 클래스를 상속받는 클래스 생성
- AARSDunMonsterCharacter
- ARSDunPlayerCharacter
베이스 클래스에 가장 기본적으로 공통되는 값들을 변수로 추가
- WalkSpeed: 이동 속도
- MaxHP: 최대 체력
- HP: 체력

[Add] 던전에서 베이스가 되는 캐릭터 클래스 추가

---

Content/Blueprints/Actor/Tycoon/BP_RSTileMap.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_BaseTile.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_RSBaseTile.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_RSTableTile.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_RSTestTile1.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_TableTile.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_TestTile.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_TestTile1.uasset
Content/Blueprints/Characters/BP_RSTycoonCharacter.uasset
Content/Blueprints/Controllers/BP_RSTycoonController.uasset
Content/Blueprints/GameMode/BP_TycoonGameMode.uasset
Content/Inputs/Tycoon/IA_TycoonInteract.uasset
Content/Inputs/Tycoon/IA_TycoonMove.uasset
Content/Inputs/Tycoon/IMC_Tycoon.uasset
Content/RogShop/Map/TycoonTestMap.umap
Source/RogShop/Actor/Tycoon/Tile/RSBaseTile.h
Source/RogShop/Character/AI/RSTycoonBaseAICharacter.cpp
Source/RogShop/Character/AI/RSTycoonBaseAICharacter.h
Source/RogShop/Character/RSTycoonCharacter.cpp
Source/RogShop/Character/RSTycoonCharacter.h
Source/RogShop/Controller/RSTycoonPlayerController.cpp
Source/RogShop/Controller/RSTycoonPlayerController.h
Source/RogShop/UtilDefine.h

#11 [Feature] 타이쿤 전용 캐릭터 제작
RSTycoonCharacter, RSTycoonPlayerController 등을 추가함 플레이어는 WASD로 움직일 수 있으며 F로 Tile과 상호작용 할 수 있음

[Add] 타이쿤 전용 플레이어 추가

---

Content/Datas/IngredientDataTable.uasset
Source/RogShop/DataTable/CookData.cpp
Source/RogShop/DataTable/CookData.h

[Add] 음식 데이터 추가

---

Content/Blueprints/Widgets/Tycoon/WBP_BartenderMenuWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_CookedBubbleWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_CustomerBubbleWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_DecoHUDWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_EnterRestaurantWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_RefrigeratorSlotWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_RefrigeratorWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_StoveSlotWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_StoveWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonOperationWidget.uasset
Source/RogShop/Widget/Tycoon/CookedBubbleWidget.cpp
Source/RogShop/Widget/Tycoon/CookedBubbleWidget.h
Source/RogShop/Widget/Tycoon/CustomerBubbleWidget.cpp
Source/RogShop/Widget/Tycoon/CustomerBubbleWidget.h
Source/RogShop/Widget/Tycoon/DecoHUDWidget.cpp
Source/RogShop/Widget/Tycoon/DecoHUDWidget.h
Source/RogShop/Widget/Tycoon/RefrigeratorSlotWidget.cpp
Source/RogShop/Widget/Tycoon/RefrigeratorSlotWidget.h
Source/RogShop/Widget/Tycoon/RefrigeratorWidget.cpp
Source/RogShop/Widget/Tycoon/RefrigeratorWidget.h
Source/RogShop/Widget/Tycoon/StoveSlotWidget.cpp
Source/RogShop/Widget/Tycoon/StoveSlotWidget.h
Source/RogShop/Widget/Tycoon/StoveWidget.cpp
Source/RogShop/Widget/Tycoon/StoveWidget.h
Source/RogShop/Widget/Tycoon/TycoonOperationWidget.cpp
Source/RogShop/Widget/Tycoon/TycoonOperationWidget.h

타이쿤 UI
식당 운영 HUD
식당 관리 HUD
화구 UI
냉장고 UI
손님 말풍선 UI 
화구 말풍선 UI
위에 것들 추가했습니다.

[Add] 타이쿤 UI 추가

---

Source/RogShop/Character/RSDunMonsterCharacter.cpp
Source/RogShop/Character/RSDunMonsterCharacter.h

간단한 PR입니다. bHasAttackTraced 관련 변수/함수가 필요없어져서 삭제했습니다.

[Fix] 실험하다가 필요없어진 변수/함수 삭제

---

Content/Assets/Worm/Animation/AS_WormAttackA.uasset
Content/Assets/Worm/Animation/AS_WormBreathAttack.uasset
Content/Assets/Worm/Animation/AS_WormBurrow.uasset
Content/Assets/Worm/Animation/AS_WormDead.uasset
Content/Assets/Worm/Animation/AS_WormDiggingUp.uasset
Content/Assets/Worm/Animation/AS_WormDive.uasset
Content/Assets/Worm/Animation/AS_WormHit.uasset
Content/Assets/Worm/Animation/AS_WormIdle.uasset
Content/Assets/Worm/Animation/AS_WormSmash.uasset
Content/Assets/Worm/SK_Worm.uasset
Content/Assets/Worm/SK_Worm_PhysicsAsset.uasset
Content/Assets/Worm/SK_Worm_Skeleton.uasset
Content/Assets/Worm/Texture/Worm_BaseColor.uasset
Content/Assets/Worm/Texture/Worm_BaseColor_B.uasset
Content/Assets/Worm/Texture/Worm_Emissive.uasset
Content/Assets/Worm/Texture/Worm_Emissive2.uasset
Content/Assets/Worm/Texture/Worm_Normal.uasset
Content/Assets/Worm/Texture/Worm_OcclusionRoughnessMetallic.uasset
Content/Assets/Worm/lambert2.uasset

애셋의 머티리얼에 문제가 있어서 바로 추가하지 않았던 애셋 추가
서승우님이 머티리얼 문제를 해결해주시기로 하셨습니다.

[Add] 웜 애셋 추가

---

Content/BehaviorTrees/Monsters/BB_MonsterBase.uasset
Content/BehaviorTrees/Monsters/BTT_CombatChoice.uasset
Content/BehaviorTrees/Monsters/BT_SpiderQueen.uasset
Content/BehaviorTrees/Monsters/EnumCombatChoice.uasset
Content/Blueprints/Controllers/BP_MonsterAIController.uasset
Content/Blueprints/Controllers/BP_SpiderQueenAIController.uasset

[ADD] SpiderQueen Boss AI Behavior Prototype

---

Config/DefaultEngine.ini

GameDefaultMap을 MainMenuMap으로 변경
EditorStartupMap을 MainMenuMap으로 변경
ServerDefaultMap을 None으로 변경

[Update] GameMapsSettings의 맵 설정 수정

---

Content/Blueprints/GameMode/BP_RSDungeonGameMode.uasset
Content/Maps/ForestMap.umap
Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp
Source/RogShop/GameModeBase/RSDungeonGameModeBase.h

AGameModeBase를 상속받은 게임모드 추가
해당 게임모드에 던전에서 사용할 플레이어 캐릭터 및 컨트롤러 오버라이드
던전인 ForestMap에 해당 게임모드 오버라이드

[Add] 던전 게임모드 추가

---

Config/DefaultGame.ini
Content/Blueprints/GameMode/BP_RSDungeonGameMode.uasset
Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp
Source/RogShop/Actor/MapGenerator/RSSpawnManager.h
Source/RogShop/GameInstanceSubsystem/RSDataSubsystem.cpp
Source/RogShop/GameInstanceSubsystem/RSDataSubsystem.h
Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp
Source/RogShop/GameModeBase/RSDungeonGameModeBase.h
Source/RogShop/RSDataSubsystemSettings.h

[Update] RsDataSubsystemSettings.h에 MonsterSate DataBase추가 및 ProjectSettings에도 추가 / 몬스터 생성로직 수정 / 현재 정상적으로 DataBase의 Count만큼 생성되나 중심축이 가운데 있어 발밑으로 수정 필요/ 게임모드에 SpawnManger유효성 검사 추가

[Update]Feature/fixed spawn manager

---

Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp

몬스터와 플레이어의 스폰 로케이션이 땅의 표면인데, 몬스터와 플레이어의 피벗이 캐릭터의 중심에 위치해 바닥을 뚫린 상태로 스폰되는 문제가 있었습니다.
플레이어 캐릭터와 각 몬스터의 크기가 다르다는 점을 고려하여 해당 문제를 수정해야했습니다.
단순하게 땅의 표면으로부터 특정 거리를 두어 스폰시키면 몬스터별로 크기가 다르기 때문에 크기가 작은 몬스터는 공중에 뜬 상태로 스폰될 것이고, 크기가 큰 몬스터는 기존대로 바닥을 뚫고 스폰될 것입니다.
이를 해결하기 위해 몬스터와 플레이어 캐릭터를 스폰한 후 캡슐 컴포넌트의 높이를 구해 스폰한 위치에서 캡슐 컴포넌트의 크기만큼 더해주었습니다.

[Bugfix] 던전에서 몬스터와 플레이어 캐릭터가 땅과 겹치거나 떨어지는 현상 수정

---

Content/Blueprints/Widgets/Dungeon/WBP_DunMainHUDWidget.uasset
Content/Blueprints/Widgets/InGam/WBP_InGameMenuWidget.uasset
Content/Blueprints/Widgets/InGame/WBP_InGameMenuWidget.uasset

content의 widget에서 InGame이 아니고 InGam으로 입력되어 다시 재수정

[Fix] 잘못된 폴더 이름 수정

---

Content/Assets/CarnivorousPlant/AnimMontage/AM_BossFlower_ThrowHoney.uasset
Content/Assets/SpiderQueen/AnimMontage/AM_BossSpiderQueen_ThrowWeb.uasset
Content/Blueprints/Characters/BP_DunSummonFlower.uasset
Content/Blueprints/Characters/BP_DunSummonSpider.uasset
Content/Datas/MonsterDataTable.uasset

[Update] 몬스터 데이터 테이블 내용 추가

---

Content/Blueprints/Actor/MapGenerator/BP_BossArenaPoint.uasset
Content/Blueprints/Actor/MapGenerator/BP_PotalSpawnPoint.uasset
Content/Blueprints/GameMode/BP_RSDungeonGameMode.uasset
Content/Maps/DungeonLevels/ForestLevels/LV_ForestBoss.umap
Content/Maps/DungeonLevels/ForestLevels/LV_ForestWayEnd.umap
Source/RogShop/Actor/MapGenerator/RSMapGenerator.cpp
Source/RogShop/Actor/MapGenerator/RSMapGenerator.h
Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp
Source/RogShop/Actor/MapGenerator/RSSpawnManager.h
Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp
Source/RogShop/GameModeBase/RSDungeonGameModeBase.h

보스방에 이동 포탈 생성되도록 로직 구현 /  이동 포탈 생성될때 보스 아레나 위치 넘겨줄수 있도록 로직 구현 / 보스아레나타겟포인트 생성 / 보스포탈타겟포인트 생성

[Update] 보스방 이동로직

---

Source/RogShop/Character/RSDunMonsterCharacter.cpp
Source/RogShop/Character/RSDunMonsterCharacter.h
Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp

빌드 오류 수정 및 몬스터 캐릭터의 데이터 테이블을 멤버 변수로 저장하는 변수명을 수정했습니다.
해당 멤버 변수는 후에 제거해주어야합니다.

[Fix] 빌드 오류 수정

---

Content/Assets/Stylized_Soup_Stew_Game_Ready/Materials/MI_MedievalSoupMeat.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Materials/MI_MedievalSoupMushroom.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Materials/MI_MedievalSoupVegetable.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Materials/M_MedievalSoup.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Meshes/SM_MedievalSoupMeat.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Meshes/SM_MedievalSoupMushroom.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Meshes/SM_MedievalSoupVegetable.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Textures/T_MedievalSoup_AO.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Textures/T_MedievalSoup_C.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Textures/T_MedievalSoup_N.uasset
Content/Assets/Stylized_Soup_Stew_Game_Ready/Textures/T_MedievalSoup_R.uasset

-머티리얼 인스턴스로 색상변화를 줘서 그릇 색이 조금 달라보이게 했습니다.

[Add] 세가지 스프(고기, 버섯, 채소) 애셋의 기존 텍스쳐를 활용한 머티리얼 작성 후 추가

---

Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon1.uasset
Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon2.uasset
Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon3.uasset
Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon4.uasset
Content/Blueprints/Actor/Dungeon/BP_PrototypeWeapon5.uasset

[Update] 무기들의 공격 범위를 위한 박스 콜리전 조절

---

Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp

[Fixed] 상점NPC생성 안되는 오류 해결 / 기존 Tag와 cpp파일의 태그가 달라서 생성 안되었던것 확인 / 오류 수정완료

[Fixed] 상점NPC스폰 오류 해결

---

Source/RogShop/Actor/Dungeon/Weapon/RSWeaponSpawnPadActor.cpp
Source/RogShop/Actor/MapGenerator/RSMapGenerator.cpp
Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp
Source/RogShop/ActorComponent/RSMeleeAttackBoxComponent.cpp
Source/RogShop/AnimNotify/RSAttackTraceAnimNotify.cpp
Source/RogShop/Character/RSDunMonsterCharacter.cpp
Source/RogShop/Character/Tycoon/NPC/RSTycoonNPC.cpp
Source/RogShop/Controller/RSDunPlayerController.cpp
Source/RogShop/Controller/RSTycoonPlayerController.cpp
Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp
Source/RogShop/UtilDefine.h
Source/RogShop/Widget/DunShop/RSDunItemWidget.cpp
Source/RogShop/Widget/DunShop/RSDunShopWidget.cpp
Source/RogShop/Widget/Dungeon/RSIngredientInventoryWidget.cpp
Source/RogShop/Widget/Dungeon/RSPlayerStatusWidget.cpp
Source/RogShop/Widget/Dungeon/RSRelicInventoryWidget.cpp
Source/RogShop/Widget/Dungeon/RSWeaponInventoryWidget.cpp
Source/RogShop/Widget/Tycoon/RSTycoonManagementWidget.cpp

- 현재 프로젝트 기준 모든 로그 제어될 수 있도록 변경
- 앞으로 추가되는 로그들은 전부 UtilDefine 파일 내부 매크로 함수를 사용해서 출력 필요, 원하는 출력 형태가 없을시 해당 파일에 매크로 추가해서 사용하는 작업 필요

[Refac] UE_LOG 및 DrawDebug~ 로그 전부 매크로 함수 통해서 출력할 수 있도록 변경

---

Content/Datas/AL_Datas.uasset
Content/Datas/DungeonWeaponDataTable.uasset
Content/Datas/IngredientDetailDataTable.uasset
Content/Datas/IngredientItemInfoDataTable.uasset

IngredientDetailDataTable의 상속 관계에 의한 오류 수정
DungeonWeaponDataTable의 불필요한 데이터 제거

[Fix] 데이터 테이블 오류 수정 및 불필요한 데이터 제거

---

Content/Blueprints/Actor/MapGenerator/BP_MapGenerator.uasset
Content/Blueprints/GameMode/BP_RSDungeonGameMode.uasset
Content/Blueprints/Widgets/InGame/WBP_InGameMenuWidget.uasset
Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp
Source/RogShop/Actor/MapGenerator/RSSpawnManager.h
Source/RogShop/GameModeBase/RSDungeonGameModeBase.cpp
Source/RogShop/GameModeBase/RSDungeonGameModeBase.h
Source/RogShop/Widget/InGame/RSInGameMenuWidget.cpp
Source/RogShop/Widget/InGame/RSInGameMenuWidget.h

InGameMenuWidget 닫기버튼 추가 / 배경블러처리 적용 / 던전게임모드및 스폰,맵생성기 필요없는 함수및 변수 정리

[Update] InGameMenuWidget 닫기버튼 추가

---

Content/Datas/DungeonLevelDataTable.uasset
Content/Maps/DungeonLevels/CaveLevels/LV_CaveBoss.umap
Content/Maps/DungeonLevels/CaveLevels/LV_CaveCorner.umap
Content/Maps/DungeonLevels/CaveLevels/LV_CaveCross.umap
Content/Maps/DungeonLevels/CaveLevels/LV_CaveStraight.umap
Content/Maps/DungeonLevels/CaveLevels/LV_CaveTway.umap
Content/Maps/DungeonLevels/CaveLevels/LV_CaveWayEnd.umap
Content/Maps/DungeonLevels/DesertLevels/LV_DesertBoss.umap
Content/Maps/DungeonLevels/DesertLevels/LV_DesertCorner.umap
Content/Maps/DungeonLevels/DesertLevels/LV_DesertCross.umap
Content/Maps/DungeonLevels/DesertLevels/LV_DesertStraight.umap
Content/Maps/DungeonLevels/DesertLevels/LV_DesertTway.umap
Content/Maps/DungeonLevels/DesertLevels/LV_DesertWayEnd.umap

[Update] 레벨넘어갈시 플레이어 스폰안되는 오류 확인[타겟포인트 미배치로 인해 발생한걸로 확인] 수정완료 / 사막 타일,동굴 타일 타겟포인트 배치완료 / CaveMap레벨벨 데이터베이스 EndLine타일 수정

[Update] 레벨 넘어갈때 오류 수정및 타겟포인트 배치

---

Content/Blueprints/Characters/Tycoon/BP_RSTycoonCustomerCharacter.uasset
Content/Blueprints/Characters/Tycoon/BP_RSTycoonPlayerCharacter.uasset
Source/RogShop/Character/Tycoon/NPC/RSTycoonCustomerCharacter.cpp
Source/RogShop/Character/Tycoon/NPC/RSTycoonCustomerCharacter.h
Source/RogShop/Character/Tycoon/RSTycoonPlayerCharacter.cpp
Source/RogShop/Character/Tycoon/RSTycoonPlayerCharacter.h

- #231
- 타이쿤 캐릭터 및 손님 메시 SkeletalMeshMergeParams 변수 이용해서 추가

[Add] 타이쿤 캐릭터 및 손님 메시 추가

---

Content/Blueprints/AL_Blueprints.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_Drink.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_EggSoup.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_Meal.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_MeatMeal.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_MeatSoup.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_RSTempFood.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_RSTempIngredient.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_SimpleEgg.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_SimpleMeat.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_SnailSoup.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_Soup.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_Steak.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_Steak2.uasset
Content/Blueprints/Actor/Tycoon/Food/BP_TempFood.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonManagementWidget.uasset
Content/Datas/CookFoodDataTable.uasset
Content/Maps/TycoonTestMap.umap

- #310 
각 음식이 생성할 ARSBaseFood를 설정했습니다
이제 자연스러운 음식의 모습을 볼 수 있습니다
IngredientDataTable은 이미 Mesh가 설정되어 있어 딱히 수정하지 않았습니다

[Update] FoodDataTable에 수정

---

Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp

[Update] 플레이가 스폰되는 타일에는 몬스터가 스폰 되지 않도록 로직수정

[Update] 플레이가 스폰되는 타일에는 몬스터가 스폰 되지 않도록 로직수정

---

Content/Assets/Crystal_cave/Materials/MI_wood.uasset
Source/RogShop/AnimInstances/RSDunPlayerAnimInstance.cpp

[Update] 동굴에서 터널에 들어갔을때 발소리 안나던 오류 해결 / 디버그용 DrawLine제거

[Update] 동굴에서 터널에 들어갔을때 발소리 안나던 오류 해결 / 디버그용 DrawLine제거

---

Content/Datas/DungeonWeaponDataTable.uasset

- 기존 6개의 무기 이름 한글화 작업 완료
- Description에 해당 무기에 대한 간략한 설명까지 추가

[Update] 무기 이름 한글화 및 간략한 설명까지 추가

---

Content/Blueprints/Actor/Tycoon/BP_RSTileMap.uasset
Content/Blueprints/Actor/Tycoon/Tile/BP_OneTableTile.uasset
Content/Blueprints/Controllers/BP_TycoonPlayerController.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonWaitWidget.uasset
Content/Maps/TycoonTestMap.umap
Source/RogShop/Actor/Tycoon/RSTileMap.cpp
Source/RogShop/Actor/Tycoon/RSTileMap.h
Source/RogShop/Actor/Tycoon/Tile/RSBaseTile.h
Source/RogShop/Actor/Tycoon/Tile/RSCookingTile.cpp
Source/RogShop/Actor/Tycoon/Tile/RSDoorTile.h
Source/RogShop/ActorComponent/RSTycoonInventoryComponent.cpp
Source/RogShop/ActorComponent/RSTycoonInventoryComponent.h
Source/RogShop/GameModeBase/RSTycoonGameModeBase.cpp
Source/RogShop/Widget/Tycoon/RSTycoonBuyNPCWidget.cpp
Source/RogShop/Widget/Tycoon/RSTycoonManagementWidget.cpp
Source/RogShop/Widget/Tycoon/RSTycoonSaleResultWidget.cpp
Source/RogShop/Widget/Tycoon/RSTycoonWaitWidget.cpp
Source/RogShop/Widget/Tycoon/RSTycoonWaitWidget.h

- #360 
문, 화구, 테이블이 최소 하나씩 있지 않으면 운영을 시작할 수 없게 변경

[Update] 운영 시작 최소 타일을 설정

---

Content/Blueprints/Audio/Bush/BushSounds_Cue.uasset
Source/RogShop/Actor/MapGenerator/RSBushTriggerSoundActor.cpp
Source/RogShop/Character/RSDunMonsterCharacter.cpp

[Update] 몬스터가 부쉬 밟을때도 소리가 나게 설정 / 부쉬소리 Attenuation설정 포함

[Update] 몬스터가 부쉬 밟을때도 소리가 나게 설정 / 부쉬소리 Attenuation설정 포함

---

Content/Blueprints/Audio/SoundCue/WeaponSwingSound/BattleAxe_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/GreatSword_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Hammer_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Hatchet_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Mace_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Strong_BattleAxe_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Strong_GreatSword_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Strong_Hammer_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Strong_Hatchet_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Strong_Mace_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Strong_Sword_Swing_Cue.uasset
Content/Blueprints/Audio/SoundCue/WeaponSwingSound/Sword_Swing_Cue.uasset

[Del] 사용하지 않게된 기존에 생성했던 무기 휘두르는 사운드 삭제

---

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundWeapon.cpp
Source/RogShop/Actor/Dungeon/Weapon/RSBaseWeapon.cpp
Source/RogShop/Actor/Dungeon/Weapon/RSBaseWeapon.h
Source/RogShop/ActorComponent/RSPlayerWeaponComponent.cpp
Source/RogShop/ActorComponent/RSPlayerWeaponComponent.h
Source/RogShop/AnimNotifyState/RSAttackAnimNotifyState.cpp
Source/RogShop/Widget/DunShop/RSDunItemWidget.cpp

무기의 액터에 나이아가라 컴포넌트를 사용해 이펙트가 꺼지거나 켜지도록 해주었습니다.
Trail 기능이 꺼지고, 켜지는 시점은 무기의 충돌 판정이 시작되고 꺼지는 스테이트의 Begin과 End입니다.

[Update] 무기 공격 시 무기를 따라 그려지는 이펙트 구현

---

Content/Blueprints/Widgets/Dungeon/WBP_PlayerDeathWidget.uasset

사망 화면에서 '거점으로' 버튼의 크기를 조정하였습니다.

[Update] 사망 화면 UI 버튼 크기 조정

---

Content/Blueprints/Widgets/Dungeon/WBP_MonsterHPBarWidget.uasset
Source/RogShop/Controller/RSMonsterAIController.cpp

[Update] 일반 몬스터 체력바 UI 가시성 개선 

---

Content/Datas/WeaponDetailDataTable.uasset

[Update] 수정 된 무기 데이터 테이블 애니메이션 수정

---

Content/Assets/SwordTrailVFX/VFX/NS_Trail_04.uasset

NS_Trail_04 이펙트에 변수 User.EffectWidth와 User.EffectPosition을 추가하였습니다.

[Update] NS_Trail_04 이펙트 변수 추가

---

Content/Blueprints/Audio/SoundCue/BaseArea_BGM.uasset
Content/Maps/BaseAreaMap.umap

[Add] 거점 BGM 추가

---

Content/Assets/DrapEffet/Meterials/M_beam.uasset
Content/Assets/DrapEffet/VFX/NE_drop_effect05.uasset
Content/Assets/DrapEffet/VFX/NE_drop_effects06.uasset
Content/Assets/DrapEffet/VFX/NE_drop_effects07.uasset

드랍아이템과 거점 무기와 유물에 붙는 강조 이펙트 밝기와 형태 등을 조정하였습니다.

[Update] 드랍아이템 이펙트 밝기 및 형태 조정

---

Content/Blueprints/Widgets/MainMenu/WBP_OptionMenu.uasset
Source/RogShop/Widget/MainMenu/OptionMenuWidget.cpp

LoadSetting에서 슬라이더 값 갱신
슬라이더 기본 값 중간(0.5)로 설정

[Fix] 옵션 세팅값 저장 수정 및 기본값 설정

---

Content/Assets/UI/Image/T_ControlKeyInfo.uasset
Content/Assets/UI/Image/T_HelpWindow.uasset
Content/Assets/UI/Image/T_ListButton.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonBuyNPCWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonBuyTileWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonEventViewWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonInventorySlotWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonInventoryWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonManagementWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonSaleWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonWaitWidget.uasset

도움말과 키 조작 안내 UI 이미지를 추가하고 타이쿤의 UI 를 개선하였습니다.

[Update] UI 이미지 추가 및 UI 수정

---

Content/Datas/MonsterDataTable.uasset
Content/Datas/RelicDetailDataTable.uasset
Content/Datas/WeaponDetailDataTable.uasset

[update] 무기데미지 상위 무기 소폭 상향 및 조정, 숲 몬스터 채력 하향 조정, 동굴 및 사막 몬스터 채력 상향 조정, 유물 성장치 유보

[update] 무기데미지, 몬스터 채력, 유물 성장치 조정

---

Content/Blueprints/Actor/Dungeon/BP_DunLifeEssenceShop.uasset
Source/RogShop/Actor/Dungeon/RSDunLifeEssenceShop.cpp
Source/RogShop/Actor/Dungeon/RSDunLifeEssenceShop.h

상점에 BoxComponent를 사용하여 다른 오브젝트들을 Block 할 수 있도록 해주었습니다.

[Update] 상점이 다른 오브젝트들을 Block하도록 변경

---

Content/Assets/UI/Image/T_RecipeWindow.uasset
Content/Assets/UI/Image/T_SlideCursorVert.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonFoodListButtonWidget.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonFoodListWidget.uasset

레시피테이블 상호작용시 팝업되는 UI의 위젯을 업데이트하였습니다.
- 기존 도움말 화면의 UI와 톤을 일치시켰습니다.

[Update] 레시피테이블 UI 업데이트

---

Content/Blueprints/Widgets/Dungeon/WBP_GameInfoWidget01.uasset
Content/Blueprints/Widgets/Dungeon/WBP_GameInfoWidget02.uasset
Content/Blueprints/Widgets/Dungeon/WBP_GameInfoWidget03.uasset
Content/Blueprints/Widgets/Dungeon/WBP_GameInfoWidget04.uasset
Content/Blueprints/Widgets/Dungeon/WBP_GameInfoWidget05.uasset

게임 흐름 그림 안내 UI의 방향버튼과 확인버튼의 이미지를 수정하였습니다.

[Update] 심플 흐름 안내 UI 버튼 이미지 수정

---

Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp

[Fixed] 제단 생성될때 index오류 발생하는 문제 해결

[Fixed] 제단 생성될때 index오류 발생하는 문제 해결

---

Content/BehaviorTrees/Monsters/eqstest.uasset
Content/Maps/MonsterControllerTestMap.umap

eqs test pawn, controller test map 삭제

[Delete] 불필요 파일 삭제

---

Source/RogShop/Widget/Dungeon/RSRelicInventoryWidget.cpp
Source/RogShop/Widget/Dungeon/RSRelicInventoryWidget.h

유물 인벤토리의 UI 슬롯은 동적으로 생성되도록 변경했습니다.
유물이 없는 경우 0칸이며 획득하게 되는 경우 1칸씩 생기며 바로 유물에 대한 아이콘이 생성됩니다.

[Update] 유물 인벤토리의 슬롯은 동적으로 생성되도록 변경

---

Source/RogShop/Actor/MapGenerator/RSTileTrigger.cpp

[Fixed]미니맵에 플레이어 위치에 따라 그 점 찍히는게 1번이상 간 곳으로 되돌아가면 적용이 안되는 오류 해결

[Fixed]미니맵에 플레이어 위치에 따라 그 점 찍히는게 1번이상 간 곳으로 되돌아가면 적용이 안되는 오류 해결

---

Content/Datas/MonsterDataTable.uasset
Content/Datas/WeaponDetailDataTable.uasset

[update] 사막 몬스터 상향, 동굴 몬스터 상향, 기본무기 죽창 상향, 고가 상점무기류 하향 조정

[update] 사막 몬스터 상향, 동굴 몬스터 상향, 기본무기 죽창 상향, 고가 상점무기류 하향 조정

---

Content/Datas/GuideDataTable.uasset

[Fix] 가이드 내용 일부 수정

---

Content/Assets/PlayerAnimations/Weapon/KnightGreatsword/StrongAttack/Anim_CK2_ComboAttack02_02_RM_Montage.uasset
Content/Blueprints/Actor/Dungeon/Relic/BP_AttackSpeed_Relic.uasset
Content/Datas/RelicInfoDataTable.uasset
Content/Datas/WeaponDetailDataTable.uasset
Source/RogShop/ActorComponent/RSBaseInventoryComponent.cpp

데이터 테이블의 잘못된 값 수정
인벤토리 UI가 잘못 갱신되는 문제 수정
인벤토리에 재료가 추가되는 슬롯 설정이 잘못 되어있었습니다.

[FIx] 데이터 테이블 값 및 인벤토리 UI 버그 수정

---

Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundRelic.cpp
Source/RogShop/Actor/Dungeon/GroundItem/RSDungeonGroundRelic.h
Source/RogShop/Actor/MapGenerator/RSSpawnManager.cpp
Source/RogShop/ActorComponent/RSRelicInventoryComponent.cpp
Source/RogShop/ActorComponent/RSRelicInventoryComponent.h
Source/RogShop/CheatManager/RSCheatManager.cpp
Source/RogShop/CheatManager/RSCheatManager.h
Source/RogShop/Widget/DunShop/RSDunItemWidget.cpp

플레이어의 유물 컴포넌트에서 스폰, 적용 및 관리하도록 로직 수정
치트매니저에서 재화를 스폰시킬 수 있는 명령어 추가

[Fix] 상점에서 유물을 획득할 경우 프로그램이 터지는 문제 수정

---

Source/RogShop/ActorComponent/RSBaseInventoryComponent.cpp
Source/RogShop/ActorComponent/RSBaseInventoryComponent.h
Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.cpp
Source/RogShop/ActorComponent/RSDungeonIngredientInventoryComponent.h

[Fix] 인벤토리 버그 수정

---

Content/Datas/MonsterDataTable.uasset
Content/Datas/RelicInfoDataTable.uasset
Source/RogShop/Actor/Dungeon/RSDunNextStagePortal.cpp

일부 몬스터의 체력을 감소했습니다.
번개 유물에 해당 메시 적용

[Fix] 일부 몬스터 체력 감소

---

Source/RogShop/Actor/Dungeon/Altar/RSLifeEssenceToConversionAltar.cpp

재단에서 스폰하는 무기 및 유물의 위치를 수정했습니다.

[Fix] 재단에서 스폰하는 무기 및 유물의 위치 수정

---

Content/Blueprints/Actor/Tycoon/BP_RSTileMap.uasset
Content/Blueprints/Controllers/BP_TycoonPlayerController.uasset
Content/Blueprints/Widgets/Tycoon/WBP_TycoonManagementWidget.uasset
Content/Maps/TycoonMap.umap
Source/RogShop/Controller/RSTycoonPlayerController.cpp
Source/RogShop/Controller/RSTycoonPlayerController.h

타이쿤 카메라의 줌 인/아웃 최소값, 최대값을 조정했습니다
타이쿤 타일맵의 최소값과 최대값을 조정했습니다

[Update] 타이쿤 카메라 줌 인/아웃 최소값, 최대값 조정, 타일 맵 크기 최소값 최대값 조정
